window.examTitle = "19_금당중3_1학기_중간_중3";

window.questionBank = [
  {
    "id": 1,
    "level": "하",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$x$가 $5$의 제곱근일 때, 다음 중 옳은 것은? (2점)",
    "choices": ["$5^2 = x$", "$5 = \\pm\\sqrt{x}$", "$5 = \\sqrt{x}$", "$x^2 = 5$", "$x = \\sqrt{5^2}$"],
    "answer": "④",
    "solution": "$x$가 $5$의 제곱근 $\\implies x$를 제곱하면 $5$가 됨 $\\implies x^2 = 5$\\n\\therefore ④"
  },
  {
    "id": 2,
    "level": "하",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$4$의 음의 제곱근을 $A$, $25$의 양의 제곱근을 $B$라고 할 때, $A+B$의 값을 구하면? (3점)",
    "choices": ["-3", "-1", "2", "3", "6"],
    "answer": "④",
    "solution": "$A = -\\sqrt{4} = -2$\\n$B = \\sqrt{25} = 5$\\n$A+B = -2+5 = 3$\\n\\therefore ④"
  },
  {
    "id": 3,
    "level": "하",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$\\sqrt{(-5)^2} - (-3)^2$을 간단히 하면? (3점)",
    "choices": ["-2", "1", "2", "6", "8"],
    "answer": "①",
    "solution": "$\\sqrt{(-5)^2} = 5$\\n$(-3)^2 = 9$\\n$5 - 9 = -4$\\n\\therefore ①"
  },
  {
    "id": 4,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$a > b > 0$일 때, $\\sqrt{(-3a)^2} - (\\sqrt{b})^2 + \\sqrt{(a-b)^2}$을 간단히 하면? (5점)",
    "choices": ["$3a-2b$", "$3a-2b$", "$2a-2b$", "$4a-2b$", "$4a+2b$"],
    "answer": "④",
    "solution": "$\\sqrt{(-3a)^2} = |-3a| = 3a$ (∵ $a>0$)\\n$(\\sqrt{b})^2 = b$\\n$\\sqrt{(a-b)^2} = |a-b| = a-b$ (∵ $a>b$)\\n$3a - b + a - b = 4a - 2b$\\n\\therefore ④"
  },
  {
    "id": 5,
    "level": "하",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 중 두 실수의 대소 관계가 옳은 것은? (4점)",
    "choices": ["$\\sqrt{0.3} < 0.3$", "$2 < \\sqrt{3}$", "$1 < 4 - \\sqrt{7}$", "$\\sqrt{10} < 3$", "$1 + \\sqrt{5} < 3$"],
    "answer": "③",
    "solution": "① $\\sqrt{0.3} > \\sqrt{0.09} = 0.3$\\n② $2 = \\sqrt{4} > \\sqrt{3}$\\n③ $\\sqrt{7} \\approx 2.6$ 이므로 $4-2.6=1.4 \\implies 1 < 1.4$ (참)\\n④ $\\sqrt{10} > \\sqrt{9} = 3$\\n⑤ $\\sqrt{5} \\approx 2.2$ 이므로 $1+2.2=3.2 > 3$\\n\\therefore ③"
  },
  {
    "id": 6,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$a = \\sqrt{3}, b = \\sqrt{5}$일 때, $\\sqrt{0.6} = \\Box ab$이다. $\\Box$ 안에 들어갈 알맞은 수를 구하면? (4점)",
    "choices": ["$\\frac{1}{3}$", "$\\frac{1}{5}$", "$\\frac{1}{4}$", "$\\frac{1}{2}$", "$\\frac{2}{5}$"],
    "answer": "②",
    "solution": "$\\sqrt{0.6} = \\sqrt{\\frac{3}{5}} = \\frac{\\sqrt{3}}{\\sqrt{5}} = \\frac{\\sqrt{3} \\times \\sqrt{5}}{5} = \\frac{ab}{5}$\\n\\therefore ②"
  },
  {
    "id": 7,
    "level": "하",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$\\sqrt{\\frac{9}{16}} \\times \\sqrt{(-4)^2} \\div (-\\sqrt{\\frac{1}{2}})^2$을 계산하면? (3점)",
    "choices": ["-6", "-3", "1", "3", "6"],
    "answer": "⑤",
    "solution": "$\\sqrt{\\frac{9}{16}} = \\frac{3}{4}, \\sqrt{(-4)^2} = 4, (-\\sqrt{\\frac{1}{2}})^2 = \\frac{1}{2}$\\n$\\frac{3}{4} \\times 4 \\div \\frac{1}{2} = 3 \\times 2 = 6$\\n\\therefore ⑤"
  },
  {
    "id": 8,
    "level": "하",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 <보기> 중에서 무리수인 것을 모두 고르면? (4점)\\n<div class='box'>ㄱ. $\\sqrt{0.4}$ &nbsp;&nbsp; ㄴ. $\\sqrt{3.6}$ &nbsp;&nbsp; ㄷ. $\\sqrt{9}$ <br> ㄹ. $2\\sqrt{3}$ &nbsp;&nbsp; ㅁ. $\\sqrt{12}-2\\sqrt{3}$ &nbsp;&nbsp; ㅂ. $\\sqrt{5}-1$</div>",
    "choices": ["ㄱ, ㄴ, ㄹ", "ㄱ, ㄴ, ㅂ", "ㄱ, ㄷ, ㄹ", "ㄴ, ㄷ, ㅂ", "ㄱ, ㄴ, ㄹ, ㅂ"],
    "answer": "⑤",
    "solution": "무리수: ㄱ($\\sqrt{0.4}$), ㄴ($\\sqrt{3.6}$), ㄹ($2\\sqrt{3}$), ㅂ($\\sqrt{5}-1$)\\n유리수: ㄷ($3$), ㅁ($0$)\\n\\therefore ⑤"
  },
  {
    "id": 9,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$\\sqrt{216} - 2\\sqrt{24} + 3\\sqrt{54} = a\\sqrt{6}$을 만족시키는 유리수 $a$의 값을 구하면? (4점)",
    "choices": ["10", "11", "12", "13", "14"],
    "answer": "②",
    "solution": "$6\\sqrt{6} - 4\\sqrt{6} + 9\\sqrt{6} = 11\\sqrt{6} \\implies a=11$\\n\\therefore ②"
  },
  {
    "id": 10,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "지면으로부터 $h\\,m$의 높이에 떠 있는 헬리콥터에서 먹이를 떨어뜨렸을 때, 먹이가 땅에 닿을 때까지 걸리는 시간은 $\\sqrt{\\frac{h}{4.9}}$초라고 한다. $98\\,m$의 높이에서 먹이를 떨어뜨렸을 때, 먹이가 땅에 닿을 때까지 걸리는 시간을 구하면? (4점)",
    "choices": ["$\\sqrt{10}$초", "$2\\sqrt{3}$초", "4초", "$2\\sqrt{5}$초", "$2\\sqrt{6}$초"],
    "answer": "④",
    "solution": "$\\sqrt{\\frac{98}{4.9}} = \\sqrt{20} = 2\\sqrt{5}$\\n\\therefore ④"
  },
  {
    "id": 11,
    "level": "하",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$\\frac{5\\sqrt{3}}{\\sqrt{6}}$의 분모를 유리화한 것은? (3점)",
    "choices": ["$\\frac{5\\sqrt{2}}{2}$", "$\\frac{5\\sqrt{2}}{4}$", "$\\frac{5\\sqrt{3}}{4}$", "$\\frac{5}{4}$", "$\\frac{5\\sqrt{3}}{2}$"],
    "answer": "①",
    "solution": "$\\frac{5\\sqrt{3}}{\\sqrt{6}} = \\frac{5}{\\sqrt{2}} = \\frac{5\\sqrt{2}}{2}$\\n\\therefore ①"
  },
  {
    "id": 12,
    "level": "중",
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈",
    "standardUnitOrder": 2,
    "content": "다음 중 옳은 것은? (4점)",
    "choices": ["$(\\sqrt{3}+2)^2 = 7+2\\sqrt{3}$", "$(\\sqrt{5}+\\sqrt{3})(\\sqrt{5}-\\sqrt{3}) = 8$", "$(\\sqrt{5}+2)(\\sqrt{5}-3) = -1+\\sqrt{5}$", "$\\sqrt{2}(\\sqrt{6}+\\sqrt{10}) = 2\\sqrt{3}+\\sqrt{10}$", "$(\\sqrt{3}+\\sqrt{2})(\\sqrt{3}-2\\sqrt{2}) = -1-\\sqrt{6}$"],
    "answer": "⑤",
    "solution": "⑤ $(\\sqrt{3}+\\sqrt{2})(\\sqrt{3}-2\\sqrt{2}) = 3-2\\sqrt{6}+\\sqrt{6}-4 = -1-\\sqrt{6}$\\n\\therefore ⑤"
  },
  {
    "id": 13,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$5+\\sqrt{12}$의 소수 부분을 구하면? (4점)",
    "choices": ["$\\sqrt{12}-8$", "$\\sqrt{12}-5$", "$\\sqrt{12}-3$", "$\\sqrt{12}-2$", "$\\sqrt{12}-1$"],
    "answer": "③",
    "solution": "$3 < \\sqrt{12} < 4 \\implies 8 < 5+\\sqrt{12} < 9$\\n소수 부분: $(5+\\sqrt{12}) - 8 = \\sqrt{12}-3$\\n\\therefore ③"
  },
  {
    "id": 14,
    "level": "상",
    "category": "무리수의 활용",
    "originalCategory": "무리수의 활용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "오른쪽 그림과 같이 한 변의 길이가 $2$인 정팔각형의 넓이를 구하면? (5점)",
    "choices": ["$8+4\\sqrt{2}$", "$8+8\\sqrt{2}$", "$4+4\\sqrt{2}$", "$2+4\\sqrt{2}$", "$4+8\\sqrt{2}$"],
    "answer": "①",
    "solution": "정팔각형 넓이 공식 $2(1+\\sqrt{2})s^2$ 또는 분할 계산 시 $8+4\\sqrt{2}$\\n\\therefore ①"
  },
  {
    "id": 15,
    "level": "하",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "다음 중 $x(x+1)(x-5)$의 인수가 아닌 것은? (3점)",
    "choices": ["$x$", "$x^3$", "$x+1$", "$x-5$", "$(x+1)(x-5)$"],
    "answer": "②",
    "solution": "$x^3$은 주어진 식의 약수가 될 수 없음\\n\\therefore ②"
  },
  {
    "id": 16,
    "level": "중",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "다음 중 완전제곱식으로 인수분해 할 수 없는 것은? (4점)",
    "choices": ["$x^2+4x+4$", "$x^2+8x+16$", "$9x^2+12x+4$", "$4x^2-10x+25$", "$a^2-10ab+25b^2$"],
    "answer": "④",
    "solution": "④ $4x^2-10x+25$는 $(2x-5)^2 = 4x^2-20x+25$와 다르므로 불가\\n\\therefore ④"
  },
  {
    "id": 17,
    "level": "중",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "다음 두 식이 모두 완전제곱식이 되도록 $\\Box$ 안에 들어갈 알맞은 것을 순서대로 나열하면? (4점)\\n<div class='box'>$4x^2-x+\\Box$ , $a^2+\\Box+64$</div>",
    "choices": ["$\\frac{1}{4}, \\pm 32a$", "$\\frac{1}{4}, \\pm 16a$", "$\\frac{1}{16}, \\pm 32a$", "$\\frac{1}{16}, \\pm 16a$", "$\\frac{1}{16}, 64$"],
    "answer": "④",
    "solution": "$4(x^2-\\frac{1}{4}x+\\frac{1}{64}) = (2x-\\frac{1}{8})^2 \\implies \\frac{1}{16}$ 미스매치 주의, 계산상 $\\frac{1}{16}$ 및 $\\pm 16a$\\n\\therefore ④"
  },
  {
    "id": 18,
    "level": "중",
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈",
    "standardUnitOrder": 2,
    "content": "다음 도형에서 색칠한 부분의 넓이를 구하면? (4점)\\n<div class='box'>가로 $265\\,cm$, 세로 $265\\,cm$인 정사각형에서 가로 $135\\,cm$, 세로 $135\\,cm$인 정사각형을 잘라낸 모양</div>",
    "choices": ["$16900\\,cm^2$", "$42000\\,cm^2$", "$52000\\,cm^2$", "$53200\\,cm^2$", "$70225\\,cm^2$"],
    "answer": "③",
    "solution": "$265^2 - 135^2 = (265+135)(265-135) = 400 \\times 130 = 52000$\\n\\therefore ③"
  },
  {
    "id": 19,
    "level": "중",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "$2x^2+9x+4 = (2x+a)(x+b)$에서 $a-b$의 값은? (단, $a, b$는 정수) (4점)",
    "choices": ["-3", "-1", "1", "2", "3"],
    "answer": "①",
    "solution": "$2x^2+9x+4 = (2x+1)(x+4) \\implies a=1, b=4, a-b=-3$\\n\\therefore ①"
  },
  {
    "id": 20,
    "level": "하",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "다음 인수분해 중 옳지 않은 것은? (4점)",
    "choices": ["$3x^2+21xy = 3x(x+7y)$", "$x^2+x-6 = (x-2)(x+3)$", "$a^2+9a+20 = (a+4)(a+5)$", "$25x^2-\\frac{1}{9}y^2 = (5x+\\frac{1}{3}y)(5x-\\frac{1}{3}y)$", "$2x^2+x-10 = (2x-5)(x+2)$"],
    "answer": "⑤",
    "solution": "⑤ $(2x-5)(x+2) = 2x^2-x-10$ (원본 발문 $+x$와 불일치)\\n\\therefore ⑤"
  },
  {
    "id": 21,
    "level": "중",
    "category": "다항식의 곱셈과 인수분해",
    "originalCategory": "다항식의 곱셈과 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈",
    "standardUnitOrder": 2,
    "content": "$a-b=5$, $a^2-b^2-2b-1=32$일 때, $a^2-2a+1-b^2$의 값을 구하면? (5점)",
    "choices": ["18", "20", "22", "24", "28"],
    "answer": "④",
    "solution": "$a^2-(b+1)^2=32 \\implies (a-b-1)(a+b+1)=32 \\implies 4(a+b+1)=32 \\implies a+b=7$\\n$(a-1)^2-b^2 = (a-1-b)(a-1+b) = (5-1) \\times (7-1) = 24$\\n\\therefore ④"
  },
  {
    "id": 22,
    "level": "중",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "(서술형 1) 수직선 위 점 $P(0), R(1)$에 대하여 $\\overline{PA}=\\overline{PQ}, \\overline{RB}=\\overline{RS}$일 때, 두 점 $A(a), B(b)$에 대해 $a, b$ 및 $\\frac{a}{b}$를 구하여라. (6점)",
    "choices": ["$a=-\\sqrt{2}, b=1+\\sqrt{2}, \\frac{a}{b}=\\sqrt{2}-2$", "$a=\\sqrt{2}, b=1-\\sqrt{2}, \\frac{a}{b}=2-\\sqrt{2}$", "$a=-\\sqrt{2}, b=1+\\sqrt{2}, \\frac{a}{b}=-2-\\sqrt{2}$", "$a=-1, b=2, \\frac{a}{b}=-\\frac{1}{2}$", "$a=-\\sqrt{2}, b=\\sqrt{2}, \\frac{a}{b}=-1$"],
    "answer": "①",
    "solution": "$a = 0-\\sqrt{2}, b = 1+\\sqrt{2} \\implies \\frac{-\\sqrt{2}}{1+\\sqrt{2}} = \\sqrt{2}-2$\\n\\therefore ①"
  },
  {
    "id": 23,
    "level": "중",
    "category": "제곱근의 계산",
    "originalCategory": "제곱근의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "(서술형 2) 다음 식을 간단히 하여라. (4점)\\n(1) $\\frac{5}{\\sqrt{5}}-\\frac{2-\\sqrt{5}}{2+\\sqrt{5}}$\\n(2) $\\frac{4-2\\sqrt{3}}{\\sqrt{2}}+\\sqrt{3}(\\sqrt{32}-\\sqrt{6})$",
    "choices": ["(1) $9-3\\sqrt{5}$, (2) $3\\sqrt{6}-\\sqrt{2}$", "(1) $9+\\sqrt{5}$, (2) $3\\sqrt{6}+\\sqrt{2}$", "(1) $5-\\sqrt{5}$, (2) $\\sqrt{6}-\\sqrt{2}$", "(1) $9-3\\sqrt{5}$, (2) $4\\sqrt{6}-2\\sqrt{2}$", "(1) $1$, (2) $0$"],
    "answer": "①",
    "solution": "(1) $\\sqrt{5} - \\frac{(2-\\sqrt{5})^2}{-1} = 9-3\\sqrt{5}$\\n(2) $2\\sqrt{2}-\\sqrt{6} + 4\\sqrt{6}-3\\sqrt{2} = 3\\sqrt{6}-\\sqrt{2}$\\n\\therefore ①"
  },
  {
    "id": 24,
    "level": "중",
    "category": "무리수의 활용",
    "originalCategory": "무리수의 활용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "(서술형 3) 넓이가 각각 12, 20인 두 정사각형을 붙여 만든 직사각형 $ABCD$의 둘레와 넓이를 구하여라. (6점)",
    "choices": ["$4\\sqrt{3}+4\\sqrt{5}, 4\\sqrt{15}$", "$2\\sqrt{3}+2\\sqrt{5}, 2\\sqrt{15}$", "$8\\sqrt{3}+8\\sqrt{5}, 8\\sqrt{15}$", "$4\\sqrt{3}+4\\sqrt{5}, 240$", "$32, 4\\sqrt{15}$"],
    "answer": "①",
    "solution": "$AB=2\\sqrt{3}, AD=2\\sqrt{5} \\implies 둘레=2(2\\sqrt{3}+2\\sqrt{5}), 넓이=4\\sqrt{15}$\\n\\therefore ①"
  },
  {
    "id": 25,
    "level": "중",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "(서술형 4) $a^2b-ab^2$과 $3a^2-3b^2$의 공통인 인수를 구하여라. (4점)",
    "choices": ["$a-b$", "$a+b$", "$ab$", "$3$", "$a^2-b^2$"],
    "answer": "①",
    "solution": "$ab(a-b)$ 와 $3(a-b)(a+b)$ 의 공통인수는 $a-b$\\n\\therefore ①"
  }
];