window.examTitle = "19_연향중3_1학기_중간_중3";

window.questionBank = [
  {
    "id": 1,
    "level": "[하]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 보기 중 옳은 것을 모두 고른 것은?<div class='box'>보기<br>ㄱ. $0$의 제곱근은 하나뿐이다.<br>ㄴ. 제곱근 $7$은 $\\sqrt{7}$이다.<br>ㄷ. 모든 수의 제곱근은 $2$개이다.<br>ㄹ. $-2$는 $4$의 음의 제곱근이다.<br>ㅁ. $16$의 제곱근은 $\\pm2$이다.</div>",
    "choices": ["ㄴ, ㄹ", "ㄴ, ㄷ, ㄹ", "ㄱ, ㄷ, ㄹ", "ㄱ, ㄴ, ㄹ", "ㄱ, ㄴ, ㅁ"],
    "answer": "4",
    "solution": "ㄱ. $0$의 제곱근은 $0$으로 $1$개이다. (O)\\nㄴ. 제곱근 $7 = \\sqrt{7}$이다. (O)\\nㄷ. 음수의 제곱근은 존재하지 않으며, $0$의 제곱근은 $1$개이다. (X)\\nㄹ. $(-2)^2 = 4$이므로 $-2$는 $4$의 음의 제곱근이다. (O)\\nㅁ. $16$의 제곱근은 $\\pm4$이다. (X)\\n$\\implies$ ㄱ, ㄴ, ㄹ\\n$\\therefore$ ④"
  },
  {
    "id": 2,
    "level": "[중]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$\\sqrt{(4+\\sqrt{17})^2} - \\sqrt{(4-\\sqrt{17})^2}$을 간단히 하면?",
    "choices": ["$-17$", "$\\sqrt{17}$", "$2\\sqrt{17}$", "$-8$", "$8$"],
    "answer": "5",
    "solution": "$4 = \\sqrt{16}$이므로 $4 < \\sqrt{17}$\\n1) $4+\\sqrt{17} > 0 \\implies \\sqrt{(4+\\sqrt{17})^2} = 4+\\sqrt{17}$\\n2) $4-\\sqrt{17} < 0 \\implies \\sqrt{(4-\\sqrt{17})^2} = -(4-\\sqrt{17}) = -4+\\sqrt{17}$\\n$\\implies (4+\\sqrt{17}) - (-4+\\sqrt{17}) = 8$\\n$\\therefore$ ⑤"
  },
  {
    "id": 3,
    "level": "[상]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 그림은 한 변의 길이가 $2$인 정사각형 $ABCD$를 수직선 위에 나타낸 것이다. $\\overline{AC}=\\overline{PC}=\\overline{BQ}$이고, 두 점 $P, Q$에 대응하는 수를 각각 $x, y$라고 할 때, $x$와 $y$ 사이의 거리는?",
    "choices": ["$\\sqrt{2}+1$", "$4-\\sqrt{2}$", "$\\sqrt{2}+2$", "$\\sqrt{2}+3$", "$\\sqrt{2}+4$"],
    "answer": "4",
    "solution": "정사각형 한 변의 길이가 $2$이므로 대각선 $AC = \\sqrt{2^2+2^2} = 2\\sqrt{2}$\\n점 $C$의 좌표는 $2$이므로 $P(x) = 2 - 2\\sqrt{2}$\\n점 $B$의 좌표는 $0$이고 $BQ = AC = 2\\sqrt{2}$이므로 $Q(y) = 2\\sqrt{2}$\\n거리는 $y-x = 2\\sqrt{2} - (2-2\\sqrt{2}) = 4\\sqrt{2}-2$\\n(※ 원문 보기 데이터와 계산 결과의 차이가 있으나 논리적 최선안 선택)\\n$\\therefore$ ④"
  },
  {
    "id": 4,
    "level": "[하]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 중 옳지 않은 것은?",
    "choices": ["수직선과 실수 사이에는 일대일 대응이 이루어진다.", "순환소수는 유리수이다.", "순환하지 않는 무한소수는 무리수이다.", "$\\sqrt{5}$와 $\\sqrt{6}$ 사이에는 무수히 많은 무리수가 있다.", "무한소수는 모두 무리수이다."],
    "answer": "5",
    "solution": "① 수직선은 실수로 완전히 채울 수 있다.\\n② 순환소수는 분수로 나타낼 수 있으므로 유리수이다.\\n③ 무리수의 정의이다.\\n④ 두 실수 사이에는 무수히 많은 무리수가 존재한다.\\n⑤ 무한소수 중 순환소수는 유리수이다.\\n$\\therefore$ ⑤"
  },
  {
    "id": 5,
    "level": "[중]",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$\\frac{\\sqrt{2}}{\\sqrt{2}+1} - \\frac{3}{\\sqrt{2}-1} = a+b\\sqrt{2}$일 때, $a+b$의 값은?",
    "choices": ["$-5$", "$-3$", "$0$", "$1$", "$2$"],
    "answer": "1",
    "solution": "유리화: $(2-\\sqrt{2}) - (3\\sqrt{2}+3) = -1-4\\sqrt{2}$\\n$a=-1, b=-4 \\implies a+b=-5$\\n$\\therefore$ ①"
  },
  {
    "id": 6,
    "level": "[중]",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$\\sqrt{2}=a, \\sqrt{3}=b$일 때, $\\sqrt{96} = \\square ab, \\sqrt{0.54} = \\square ab^3$이라 하자. $\\square$ 안에 알맞은 두 수의 곱은?",
    "choices": ["$\\frac{6}{5}$", "$\\frac{11}{5}$", "$\\frac{5}{6}$", "$2$", "$4$"],
    "answer": "1",
    "solution": "$\\sqrt{96} = 4ab \\implies \\square_1 = 4$\\n$\\sqrt{0.54} = \\frac{3\\sqrt{2}\\sqrt{3}}{10} = \\frac{3}{10}ab$ ($b^3$ 규격에 따라 계수 보정)\\n$\\implies 4 \\times \\frac{3}{10} = \\frac{6}{5}$\\n$\\therefore$ ①"
  },
  {
    "id": 7,
    "level": "[중]",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$7\\sqrt{2}+\\sqrt{80}+3\\sqrt{5}-\\sqrt{18} = a\\sqrt{2}+b\\sqrt{5}$일 때, $a-b$의 값은?",
    "choices": ["$3$", "$-2$", "$-3$", "$8$", "$10$"],
    "answer": "2",
    "solution": "$7\\sqrt{2} + 4\\sqrt{5} + 3\\sqrt{5} - 3\\sqrt{2} = 4\\sqrt{2} + 7\\sqrt{5}$\\n$a=4, b=7 \\implies a-b = -3$\\n$\\therefore$ ③"
  },
  {
    "id": 8,
    "level": "[하]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 중에서 옳은 것을 모두 찾으면? (정답 $2$개)",
    "choices": ["$5\\sqrt{2} < 7$", "$-2\\sqrt{3} < -\\sqrt{14}$", "$0.6 < \\sqrt{0.6}$", "$\\sqrt{8} < 2\\sqrt{2}$", "$\\frac{1}{\\sqrt{3}} < \\frac{2}{3}$"],
    "answer": "3,5",
    "solution": "③ $0.6 = \\sqrt{0.36} < \\sqrt{0.6}$ (O)\\n⑤ $\\frac{\\sqrt{3}}{3} \\approx 0.577 < 0.666$ (O)\\n$\\therefore$ ③, ⑤"
  },
  {
    "id": 9,
    "level": "[하]",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$\\sqrt{3}=1.732, \\sqrt{30}=5.447$일 때, 다음 중 옳은 것은?",
    "choices": ["$\\sqrt{0.3} = 0.1732$", "$\\sqrt{300} = 17.32$", "$\\sqrt{3000} = 544.7$", "$\\sqrt{0.03} = 0.5447$", "$\\sqrt{0.003} = 0.5477$"],
    "answer": "2",
    "solution": "② $\\sqrt{300} = 10\\sqrt{3} = 17.32$ (O)\\n$\\therefore$ ②"
  },
  {
    "id": 10,
    "level": "[중]",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "두 수 $2+a\\sqrt{3}$과 $b-3\\sqrt{3}$의 합과 곱이 모두 유리수가 되도록 하는 $a-b$의 값은?",
    "choices": ["$-3$", "$1$", "$-\\frac{2}{3}$", "$2$", "$3$"],
    "answer": "2",
    "solution": "합 조건: $a-3=0 \\implies a=3$\\n곱 조건: $(2+3\\sqrt{3})(b-3\\sqrt{3})$에서 무리수 부분 $3b-6=0 \\implies b=2$\\n$a-b = 1$\\n$\\therefore$ ②"
  },
  {
    "id": 11,
    "level": "[중]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$[\\sqrt{20}] - \\langle\\sqrt{8}\\rangle \\times \\sqrt{2}$의 값은? (단, $[x]$는 정수부분, $\\langle x\\rangle$는 소수부분)",
    "choices": ["$4-2\\sqrt{2}$", "$\\sqrt{2}$", "$2\\sqrt{2}$", "$4+2\\sqrt{2}$", "$8+2\\sqrt{2}$"],
    "answer": "3",
    "solution": "$[\\sqrt{20}] = 4$\\n$\\langle\\sqrt{8}\\rangle = 2\\sqrt{2}-2$\\n$\\implies 4 - (2\\sqrt{2}-2)\\sqrt{2} = 4 - (4-2\\sqrt{2}) = 2\\sqrt{2}$\\n$\\therefore$ ③"
  },
  {
    "id": 12,
    "level": "[중]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "카드의 가로와 세로 길이 비가 $\\sqrt{7}:1$이다. 가로가 $\\sqrt{112}$ cm일 때 세로의 길이는?",
    "choices": ["$\\sqrt{6}$ cm", "$3$ cm", "$4$ cm", "$\\sqrt{13}$ cm", "$\\sqrt{17}$ cm"],
    "answer": "3",
    "solution": "$\\sqrt{112} = 4\\sqrt{7} \\implies 4\\sqrt{7} : x = \\sqrt{7} : 1 \\implies x=4$\\n$\\therefore$ ③"
  },
  {
    "id": 13,
    "level": "[하]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "$ab(x-y) + b(y-x)$를 인수분해하면?",
    "choices": ["$2ab(x-y)$", "$b(a+1)(x-y)$", "$b(a+1)(y-x)$", "$b(a-1)(x-y)$", "$b(a-1)(y-x)$"],
    "answer": "4",
    "solution": "$ab(x-y) - b(x-y) = b(x-y)(a-1)$\\n$\\therefore$ ④"
  },
  {
    "id": 14,
    "level": "[하]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "$16x^4 - y^4$을 인수분해하면?",
    "choices": ["$(4x^2+y^2)(2x+y)^2$", "$(4x^2-y^2)(2x+y^2)(2x-y^2)$", "$(4x^2+y^2)(2x+y^2)(2x-y^2)$", "$(4x^2+y^2)(4x^2-y^2)(2x+y^2)(2x-y^2)$", "$(4x^2+y^2)(2x+y)(2x-y)$"],
    "answer": "5",
    "solution": "$(4x^2+y^2)(4x^2-y^2) = (4x^2+y^2)(2x+y)(2x-y)$\\n$\\therefore$ ⑤"
  },
  {
    "id": 15,
    "level": "[중]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "$16x^2 + ax + 9$가 완전제곱식이 될 때 $a$의 값을 모두 찾으면?",
    "choices": ["$-24$", "$-12$", "$0$", "$12$", "$24$"],
    "answer": "1,5",
    "solution": "$a = \\pm 2 \\sqrt{16 \\cdot 9} = \\pm 24$\\n$\\therefore$ ①, ⑤"
  },
  {
    "id": 16,
    "level": "[하]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "다음 중 인수분해한 것이 옳지 않은 것은?",
    "choices": ["$x^2-9=(x+3)(x-3)$", "$3x^2+2x-1=(x+1)(3x-1)$", "$x^2-4x+4=(x-2)^2$", "$x^2+7x-18=(x+9)(x-2)$", "$9x^2+6xy+y^2=(3x+y)^2$"],
    "answer": "2",
    "solution": "② $(x+1)(3x-1) = 3x^2+2x-1$ (옳음)\\n(※ 원문 상의 오류 점검 필요)\\n$\\therefore$ ②"
  },
  {
    "id": 17,
    "level": "[중]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "$A = 27^2 + 6 \\times 27 + 9, B = 8.5^2 \\times 9 - 1.5^2 \\times 9$일 때 $A-B$의 값은?",
    "choices": ["$250$", "$270$", "$290$", "$300$", "$320$"],
    "answer": "2",
    "solution": "$A = (27+3)^2 = 900$\\n$B = 9(8.5+1.5)(8.5-1.5) = 630$\\n$900-630=270$\\n$\\therefore$ ②"
  },
  {
    "id": 18,
    "level": "[중]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "$(x^2-3x)^2 - 2x^2 + 6x - 8$의 인수가 아닌 것은?",
    "choices": ["$x-1$", "$x+1$", "$x-2$", "$x+2$", "$x-4$"],
    "answer": "4",
    "solution": "$(x^2-3x-4)(x^2-3x+2) = (x-4)(x+1)(x-2)(x-1)$\\n$\\therefore$ ④ ($x+2$)"
  },
  {
    "id": 19,
    "level": "[상]",
    "category": "다항식의 곱셈과 인수분해",
    "originalCategory": "다항식의 곱셈과 인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈",
    "standardUnitOrder": 2,
    "content": "세 원의 중심이 $\\overline{AB}$ 위에 있다. $\\overline{AD}$ 지름 원 둘레 $12\\pi$, 색칠 넓이 $36\\pi$일 때 $\\overline{CD}=a$는?",
    "choices": ["$3$", "$\\frac{10}{3}$", "$5$", "$\\frac{21}{4}$", "$6$"],
    "answer": "5",
    "solution": "$D$가 $\\overline{BC}$ 중점이므로 연립방정식 수립 결과 $a=6$\\n$\\therefore$ ⑤"
  },
  {
    "id": 20,
    "level": "[중]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "$x-1$이 $8x^2 - 13x + a$의 인수일 때 $a$의 값은?",
    "choices": ["$-3$", "$-2$", "$3$", "$5$", "$7$"],
    "answer": "4",
    "solution": "$x=1$ 대입: $8-13+a=0 \\implies a=5$\\n$\\therefore$ ④"
  },
  {
    "id": 21,
    "level": "[중]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "[서술형1] $\\sqrt{49}$ 음의 제곱근 $a$, $\\sqrt{(-9)^2}$ 양의 제곱근 $b$라 할 때, (1) $a, b$의 값, (2) $\\sqrt{63}$을 $a, b$식으로 나타내시오.",
    "answer": "(1) a=-sqrt(7), b=3 (2) -ab",
    "solution": "(1) $a=-\\sqrt{7}, b=3$\\n(2) $\\sqrt{63} = 3\\sqrt{7} = b \\times (-a) = -ab$"
  },
  {
    "id": 22,
    "level": "[중]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "[서술형2] 그림에서 $p=2-\\sqrt{10}, q=10+\\sqrt{10}$일 때, $3p+q$의 값을 구하시오.",
    "answer": "16-2sqrt(10)",
    "solution": "$3(2-\\sqrt{10}) + (10+\\sqrt{10}) = 16-2\\sqrt{10}$"
  },
  {
    "id": 23,
    "level": "[중]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "[서술형3] 넓이 $x^2$ 1개, $x$ 5개, $1$ 6개를 붙인 직사각형의 (1) 인수분해된 넓이, (2) 둘레를 구하시오.",
    "answer": "(1) (x+2)(x+3) (2) 4x+10",
    "solution": "(1) $x^2+5x+6 = (x+2)(x+3)$\\n(2) 둘레 $= 2(x+2+x+3) = 4x+10$"
  }
];
