/**
 * AP수학 무결성 복제 엔진 v4.1 - 기출 정밀 정제 데이터
 * [주의] 원장님 지시에 따라 모든 문항의 발문, 선택지, 해설을 원문 그대로 보존함.
 */
window.examTitle = "21_동산중3_1학기_중간_중3"; // 예시 타이틀, 필요시 수정 가능

window.questionBank = [
  {
    "id": 1,
    "level": "[하]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 중 옳은 것을 고르면? [3점]",
    "choices": ["√64의 제곱근은 ±8이다.", "√(-7)²은 -7이다.", "제곱근 49는 7이다.", "√25는 ±5이다.", "모든 수의 제곱근은 두 개다."],
    "answer": "3",
    "solution": "① $\\sqrt{64}=8$의 제곱근은 $\\pm\\sqrt{8}$임. ② $\\sqrt{(-7)^{2}}=7$임. ③ 제곱근 49 = $\\sqrt{49}=7$ (참) ④ $\\sqrt{25}=5$임. ⑤ 0의 제곱근은 1개, 음수의 제곱근은 없음."
  },
  {
    "id": 2,
    "level": "[중]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "부등식 $3 < \\sqrt{5n} \\le 5$ 를 만족시키는 자연수 n의 값의 합을 구하면? [4점]",
    "choices": ["10", "11", "12", "13", "14"],
    "answer": "5",
    "solution": "각 변을 제곱하면 $9 < 5n \\le 25 \\implies 1.8 < n \\le 5$. 자연수 n은 2, 3, 4, 5이므로 합은 $2+3+4+5=14$"
  },
  {
    "id": 3,
    "level": "[중]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 중 $23^{2}=529$임을 이용하여 그 값을 구할 수 없는 것은? [4점]",
    "choices": ["√52900", "√529", "√5.29", "√0.529", "√0.0529"],
    "answer": "4",
    "solution": "소수점 이동이 짝수 칸이어야 함. ④ $\\sqrt{0.529}$는 소수점 아래 3자리이므로 $\\sqrt{529}$를 이용할 수 없음."
  },
  {
    "id": 4,
    "level": "[하]",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "√108을 $a\\sqrt{b}$로 나타낼 때, $a+b$의 값을 구하면? [3점]",
    "choices": ["7", "8", "9", "12", "13"],
    "answer": "3",
    "solution": "$\\sqrt{108} = \\sqrt{36 \\times 3} = 6\\sqrt{3}$. $a=6, b=3 \\implies a+b=9$"
  },
  {
    "id": 5,
    "level": "[하]",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "식 $2\\sqrt{18} \\div \\sqrt{6} \\times 2$ 를 간단히 하면? [3점]",
    "choices": ["2√6", "3√6", "3√3", "4√3", "5√3"],
    "answer": "4",
    "solution": "$2\\sqrt{18} \\div \\sqrt{6} \\times 2 = 2\\sqrt{3} \\times 2 = 4\\sqrt{3}$"
  },
  {
    "id": 6,
    "level": "[중]",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "식 $4\\sqrt{5} - \\sqrt{125} + 10/\\sqrt{5}$ 를 간단히 하면? [3점]",
    "choices": ["√5", "-√5", "2√5", "-2√5", "3√5"],
    "answer": "1",
    "solution": "$4\\sqrt{5} - 5\\sqrt{5} + 2\\sqrt{5} = (4-5+2)\\sqrt{5} = \\sqrt{5}$"
  },
  {
    "id": 7,
    "level": "[중]",
    "category": "근호를 포함한 식의 계산",
    "originalCategory": "근호를 포함한 식의 계산",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "식 $\\sqrt{27} + 6 \\div \\sqrt{3} - 8\\sqrt{3}$ 를 간단히 하면? [4점]",
    "choices": ["√3", "2√3", "-2√3", "3√3", "-3√3"],
    "answer": "5",
    "solution": "$3\\sqrt{3} + 2\\sqrt{3} - 8\\sqrt{3} = -3\\sqrt{3}$"
  },
  {
    "id": 8,
    "level": "[중]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "다음 두 실수의 대소비교가 틀린 것을 찾으면? [3점]",
    "choices": ["√0.04 < 0.02", "√3+1 < 3", "√7+√3 < √7+2", "1-√2 < √5-√2", "4 < 3√2"],
    "answer": "1",
    "solution": "① $\\sqrt{0.04}=0.2$이므로 $0.2 < 0.02$는 거짓임."
  },
  {
    "id": 9,
    "level": "[하]",
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈",
    "standardUnitOrder": 2,
    "content": "다음 중 식 $(2x+3)(x-4)$ 를 전개한 것은? [3점]",
    "choices": ["2x²-12", "2x²-5x-12", "2x²-4x-12", "2x²-3x+3", "2x²+3x-4"],
    "answer": "2",
    "solution": "$(2x+3)(x-4) = 2x^{2} - 8x + 3x - 12 = 2x^{2} - 5x - 12$"
  },
  {
    "id": 10,
    "level": "[중]",
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈",
    "standardUnitOrder": 2,
    "content": "$(x-2y)(x+2y-3)$ 를 전개하여 간단히 하였을 때, $xy$의 계수와 $y$ 계수의 합을 구하면? [3점]",
    "choices": ["0", "4", "-4", "6", "-6"],
    "answer": "4",
    "solution": "$x^{2}+2xy-3x-2xy-4y^{2}+6y = x^{2}-4y^{2}-3x+6y$. $xy$계수: 0, $y$계수: 6이므로 합은 6"
  },
  {
    "id": 11,
    "level": "[중]",
    "category": "분모의 유리화",
    "originalCategory": "분모의 유리화",
    "standardCourse": "중3 수학",
    "standardUnitKey": "RAW-분모의유리화",
    "standardUnit": "분모의 유리화",
    "standardUnitOrder": 999,
    "content": "식 $(\\sqrt{5}+2)/(\\sqrt{5}-2) + (\\sqrt{5}-2)/(\\sqrt{5}+2)$ 를 간단히 하면? [4점]",
    "choices": ["18", "2√5", "9+4√5", "18+8√5", "18-8√5"],
    "answer": "1",
    "solution": "유리화하면 $(9+4\\sqrt{5}) + (9-4\\sqrt{5}) = 18$"
  },
  {
    "id": 12,
    "level": "[중]",
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈",
    "standardUnitOrder": 2,
    "content": "$x$에 관한 이차식을 $(x+5)$로 나누면 몫이 $x-3$이고 나머지가 2일 때, 이 이차식을 구하면? [4점]",
    "choices": ["x²+2x+13", "x²+2x-13", "x²-2x+13", "x²+2x-15", "x²-2x-15"],
    "answer": "2",
    "solution": "$(x+5)(x-3) + 2 = (x^{2}+2x-15) + 2 = x^{2}+2x-13$"
  },
  {
    "id": 13,
    "level": "[중]",
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈",
    "standardUnitOrder": 2,
    "content": "$x=2+3\\sqrt{3}, y=2-3\\sqrt{3}$일 때, $(x+1)(y+1)-xy$ 의 값을 구하면? [4점]",
    "choices": ["0", "2√3", "4", "4√3", "5"],
    "answer": "5",
    "solution": "$(x+1)(y+1)-xy = xy+x+y+1-xy = x+y+1$. $x+y=4$이므로 $4+1=5$"
  },
  {
    "id": 14,
    "level": "[중]",
    "category": "곱셈 공식의 변형",
    "originalCategory": "곱셈 공식의 변형",
    "standardCourse": "중3 수학",
    "standardUnitKey": "RAW-곱셈공식의변형",
    "standardUnit": "곱셈 공식의 변형",
    "standardUnitOrder": 999,
    "content": "$a-b=3, a^{2}+b^{2}=13$일 때, $ab$의 값을 구하면? [4점]",
    "choices": ["2", "-2", "3", "-3", "6"],
    "answer": "1",
    "solution": "$a^{2}+b^{2} = (a-b)^{2}+2ab \\implies 13 = 3^{2}+2ab$. $2ab = 4 \\therefore ab = 2$"
  },
  {
    "id": 15,
    "level": "[중]",
    "category": "다항식의 값",
    "originalCategory": "다항식의 값",
    "standardCourse": "중3 수학",
    "standardUnitKey": "RAW-다항식의값",
    "standardUnit": "다항식의 값",
    "standardUnitOrder": 999,
    "content": "$x=3-2\\sqrt{2}$일 때, 식 $x^{2}-6x+7$의 값을 구하면? [4점]",
    "choices": ["3", "6√2", "4√2", "6", "9"],
    "answer": "4",
    "solution": "$x-3 = -2\\sqrt{2}$의 양변을 제곱하면 $x^{2}-6x+9 = 8 \\implies x^{2}-6x = -1$. 식: $-1+7=6$"
  },
  {
    "id": 16,
    "level": "[중]",
    "category": "인수분해의 활용",
    "originalCategory": "인수분해의 활용",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "곱셈공식을 이용하여 다음 식을 계산하면? [4점]\\n$2021 \\times 2023 - 4042 - 2020 \\times 2022$",
    "choices": ["0", "1", "2021", "2022", "2023"],
    "answer": "2",
    "solution": "$2021=x$로 치환: $x(x+2)-2x-(x-1)(x+1) = x^{2}+2x-2x-(x^{2}-1) = 1$"
  },
  {
    "id": 17,
    "level": "[중]",
    "category": "다항식의 곱셈",
    "originalCategory": "다항식의 곱셈",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-02",
    "standardUnit": "다항식의 곱셈",
    "standardUnitOrder": 2,
    "content": "식 $(ax-3)(2x+b)$를 전개하면 $8x^{2}+cx-15$가 된다. 이때, $a+b+c$의 값을 구하면? [4점]",
    "choices": ["5", "9", "10", "19", "23"],
    "answer": "5",
    "solution": "$2a=8 \\implies a=4$, $-3b=-15 \\implies b=5$, $c=ab-6=14$. $a+b+c = 4+5+14=23$"
  },
  {
    "id": 18,
    "level": "[하]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "다음 중 $x^{2}y-6xy^{2}$의 인수가 아닌 것은? [3점]",
    "choices": ["x", "y", "x-6y", "xy", "x²y"],
    "answer": "5",
    "solution": "$xy(x-6y)$로 인수분해됨. $x^{2}y$는 인수가 아님."
  },
  {
    "id": 19,
    "level": "[중]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "식 $x^{2}+\\Box x+1/16$ 이 완전제곱식이 되도록 하는 $\\Box$ 안의 값은? [4점]",
    "choices": ["±1", "±2", "±1/2", "±1/4", "±1/8"],
    "answer": "3",
    "solution": "$\\Box = \\pm 2 \\times \\sqrt{1 \\times \\frac{1}{16}} = \\pm 2 \\times \\frac{1}{4} = \\pm \\frac{1}{2}$"
  },
  {
    "id": 20,
    "level": "[중]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "$2 < x < 3$일 때, $\\sqrt{(x^{2}-4x+4)}-\\sqrt{(x^{2}-6x+9)}$ 를 간단히 하면? [4점]",
    "choices": ["2x-5", "2x", "2x+1", "2x-1", "5"],
    "answer": "1",
    "solution": "$|x-2|-|x-3|$. $2<x<3$이므로 $(x-2)-\\{-(x-3)\\} = 2x-5$"
  },
  {
    "id": 21,
    "level": "[중]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "식 $x^{2}+y^{2}-z^{2}-2xy$를 인수분해하면? [4점]",
    "choices": ["(x+y+z)(x+y-z)", "(x+y+z)(x-y-z)", "(x-y+z)(x-y-z)", "(x-y+z)(x+y+z)", "(x-y+z)(x+y-z)"],
    "answer": "5",
    "solution": "$(x-y)^{2}-z^{2}$ 이므로 합차 공식에 의해 $(x-y+z)(x-y-z)$"
  },
  {
    "id": 22,
    "level": "[상]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "다음 중 $2^{8}-1$의 약수가 아닌 것은? [4점]",
    "choices": ["3", "5", "15", "13", "17"],
    "answer": "4",
    "solution": "$(2^{4}+1)(2^{2}+1)(2+1)(2-1) = 17 \\times 5 \\times 3 \\times 1$. $15(5 \\times 3)$는 약수이나 $13$은 아님."
  },
  {
    "id": "서술형1",
    "level": "[중]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$2\\sqrt{3}$의 정수부분을 $a$, 소수부분을 $b$라고 할 때, $a, b$의 값과 $\\sqrt{3}a-3b$의 값을 구하여라. [7점]",
    "answer": "a=3, b=2\\sqrt{3}-3, 값: 9-3\\sqrt{3}",
    "solution": "1) $3 < \\sqrt{12} < 4 \\implies a=3$. 2) $b=2\\sqrt{3}-3$. 3) $3\\sqrt{3}-3(2\\sqrt{3}-3) = 9-3\\sqrt{3}$"
  },
  {
    "id": "서술형2",
    "level": "[중]",
    "category": "제곱근과 실수",
    "originalCategory": "제곱근과 실수",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-01",
    "standardUnit": "제곱근과 실수",
    "standardUnitOrder": 1,
    "content": "$AB=PB, CD=CQ$일 때 점 P에 대응하는 수, Q에 대응하는 수, $PQ$의 길이를 구하여라. [7점]",
    "answer": "p=2-\\sqrt{5}, q=5+\\sqrt{5}, PQ=3+2\\sqrt{5}",
    "solution": "대각선 $\\sqrt{5}$. $p=2-\\sqrt{5}, q=5+\\sqrt{5}$. $PQ = q-p = (5+\\sqrt{5})-(2-\\sqrt{5}) = 3+2\\sqrt{5}$"
  },
  {
    "id": "서술형3",
    "level": "[중]",
    "category": "인수분해",
    "originalCategory": "인수분해",
    "standardCourse": "중3 수학",
    "standardUnitKey": "M3-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "다음 두 식을 인수분해하고 공통인수를 써라. [6점]\\n$[x^{2}-4y^{2}, 3x+6y]$ ",
    "answer": "x+2y",
    "solution": "1) $(x+2y)(x-2y)$, 2) $3(x+2y)$. 공통인수는 $x+2y$임."
  }
];