window.examTitle = "25_순천여고1_1학기_중간_대수";

window.questionBank = [
    {
        id: 1,
        level: "하",
        category: "지수법칙",
        originalCategory: "지수법칙",
        standardCourse: "대수",
        standardUnitKey: "H22-C-02",
        standardUnit: "지수법칙",
        standardUnitOrder: 2,
        content: "$2^{2\\sqrt{3}} \\times 2^{3-2\\sqrt{3}}$의 값은? [3.3점]",
        choices: ["2", "4", "8", "16", "32"],
        answer: "③",
        solution: "1단계: 지수법칙 $a^m \\times a^n = a^{m+n}$을 적용한다.\\n2단계: $2^{2\\sqrt{3} + (3-2\\sqrt{3})} = 2^3$\\n3단계: $2^3 = 8$\\n* 검산: 지수 부분의 무리수 $2\\sqrt{3}$과 $-2\\sqrt{3}$이 소거되어 $2^3$이 됨을 확인."
    },
    {
        id: 2,
        level: "중",
        category: "로그방정식",
        originalCategory: "로그방정식",
        standardCourse: "대수",
        standardUnitKey: "H22-C-07",
        standardUnit: "지수·로그 방정식",
        standardUnitOrder: 7,
        content: "다음 방정식 $\\log_2 (x-3) + \\log_2 (x+3) = 4$의 해를 구하면? [3.4점]",
        choices: ["-5", "-1", "1", "5", "9"],
        answer: "④",
        solution: "1단계: 로그의 성질 $\\log_a M + \\log_a N = \\log_a MN$을 적용한다.\\n$\\log_2 (x-3)(x+3) = 4 \\Rightarrow \\log_2 (x^2-9) = 4$\\n2단계: 로그의 정의에 의해 $x^2-9 = 2^4 = 16$이므로 $x^2 = 25$이다.\\n3단계: $x = \\pm 5$이나, 로그의 진수 조건($x-3>0, x+3>0$)에 의해 $x>3$이어야 한다. 따라서 $x=5$.\\n* 검산: $x=5$ 대입 시 $\\log_2 2 + \\log_2 8 = 1+3=4$ 성립."
    },
    {
        id: 3,
        level: "중",
        category: "지수함수의 그래프",
        originalCategory: "지수함수의 그래프",
        standardCourse: "대수",
        standardUnitKey: "H22-C-03",
        standardUnit: "지수함수",
        standardUnitOrder: 3,
        content: "함수 $y=\\left(\\frac{1}{2}\\right)^x+1$의 그래프를 $y$축에 대하여 대칭이동 한 후 $x$축의 방향으로 $a$만큼, $y$축의 방향으로 $b$만큼 평행이동 하였더니 함수 $y=2^{x-3}+5$의 그래프와 일치하였다. 상수 $a, b$에 대하여 $ab$의 값은? [3.4점]",
        choices: ["-12", "-10", "8", "10", "12"],
        answer: "⑤",
        solution: "1단계: $y=\\left(\\frac{1}{2}\\right)^x+1$을 $y$축에 대하여 대칭이동하면 $x$ 대신 $-x$를 대입하므로 $y=\\left(\\frac{1}{2}\\right)^{-x}+1 = 2^x+1$이다.\\n2단계: 이 그래프를 $x$축으로 $a$, $y$축으로 $b$만큼 평행이동하면 $y=2^{x-a}+1+b$가 된다.\\n3단계: 주어진 식 $y=2^{x-3}+5$와 비교하면 $a=3, 1+b=5 \\Rightarrow b=4$이다.\\n4단계: $ab = 3 \\times 4 = 12$\\n* 검산: $a=3, b=4$ 대입 시 식이 완벽히 일치함."
    },
    {
        id: 4,
        level: "중",
        category: "로그의 계산",
        originalCategory: "로그의 계산",
        standardCourse: "대수",
        standardUnitKey: "H22-C-05",
        standardUnit: "로그의 성질",
        standardUnitOrder: 5,
        content: "다음 중 그 값이 가장 큰 것은? [3.5점]",
        choices: ["$\\log_{\\frac{1}{3}} 9$", "$\\log_5 \\sqrt{125}$", "$4^{\\log_2 3}$", "$\\log_4 8$", "$\\frac{1}{\\log_{64} 2}$"],
        answer: "③",
        solution: "1단계: 각 보기의 값을 계산한다.\\n① $\\log_{3^{-1}} 3^2 = -2$\\n② $\\log_5 5^{\\frac{3}{2}} = \\frac{3}{2} = 1.5$\\n③ $4^{\\log_2 3} = (2^2)^{\\log_2 3} = 2^{2\\log_2 3} = 2^{\\log_2 9} = 9$\\n④ $\\log_{2^2} 2^3 = \\frac{3}{2} = 1.5$\\n⑤ $\\log_2 64 = \\log_2 2^6 = 6$\\n2단계: 비교 결과 $9$가 가장 크다.\\n* 검산: $9 > 6 > 1.5 > -2$ 순서 확인."
    },
    {
        id: 5,
        level: "하",
        category: "일반각",
        originalCategory: "일반각",
        standardCourse: "대수",
        standardUnitKey: "H22-C-09",
        standardUnit: "삼각함수의 뜻과 값",
        standardUnitOrder: 9,
        content: "각을 $360^{\\circ} \\times n + \\alpha^{\\circ}$ ($n$은 정수, $0^{\\circ} \\le \\alpha^{\\circ} < 360^{\\circ}$)의 꼴로 나타낼 때 다음 중 $\\alpha$의 값이 가장 큰 것은? [3.6점]",
        choices: ["-1100", "-500", "500", "1100", "2000"],
        answer: "①",
        solution: "1단계: 각 보기의 $\\alpha$를 구한다.\\n① $-1100^{\\circ} = 360^{\\circ} \\times (-4) + 340^{\\circ} \\Rightarrow \\alpha=340$\\n② $-500^{\\circ} = 360^{\\circ} \\times (-2) + 220^{\\circ} \\Rightarrow \\alpha=220$\\n③ $500^{\\circ} = 360^{\\circ} \\times 1 + 140^{\\circ} \\Rightarrow \\alpha=140$\\n④ $1100^{\\circ} = 360^{\\circ} \\times 3 + 20^{\\circ} \\Rightarrow \\alpha=20$\\n⑤ $2000^{\\circ} = 360^{\\circ} \\times 5 + 200^{\\circ} \\Rightarrow \\alpha=200$\\n2단계: 가장 큰 값은 $340$이다.\\n* 검산: $0 \\le \\alpha < 360$ 조건을 모두 만족함."
    },
    {
        id: 6,
        level: "중",
        category: "삼각함수 사이의 관계",
        originalCategory: "삼각함수 사이의 관계",
        standardCourse: "대수",
        standardUnitKey: "RAW-삼각함수사이의관계",
        standardUnit: "삼각함수 사이의 관계",
        standardUnitOrder: 999,
        content: "$\\sin\\theta + \\cos\\theta = \\frac{1}{5}$일 때, $\\sin\\theta\\cos\\theta$의 값은? [3.7점]",
        choices: ["$-\\frac{12}{25}$", "$\\frac{12}{25}$", "$-\\frac{24}{25}$", "$\\frac{24}{25}$", "$-\\frac{4}{25}$"],
        answer: "①",
        solution: "1단계: 주어진 식의 양변을 제곱하면 $(\\sin\\theta + \\cos\\theta)^2 = \\left(\\frac{1}{5}\\right)^2$이다.\\n2단계: $\\sin^2\\theta + 2\\sin\\theta\\cos\\theta + \\cos^2\\theta = \\frac{1}{25}$이므로 $1 + 2\\sin\\theta\\cos\\theta = \\frac{1}{25}$이다.\\n3단계: $2\\sin\\theta\\cos\\theta = \\frac{1}{25} - 1 = -\\frac{24}{25}$이므로 $\\sin\\theta\\cos\\theta = -\\frac{12}{25}$이다.\\n* 검산: 곱셈공식에 따른 전개 및 이항 결과가 정확함."
    },
    {
        id: 7,
        level: "중",
        category: "지수법칙",
        originalCategory: "지수법칙",
        standardCourse: "대수",
        standardUnitKey: "H22-C-02",
        standardUnit: "지수법칙",
        standardUnitOrder: 2,
        content: "실수 $x$에 대하여 $\\frac{a^x - a^{-x}}{a^x + a^{-x}} = \\frac{1}{2}$일 때, $\\frac{a^{2x} + a^{-2x}}{a^{2x} - a^{-2x}}$의 값은? (단, $a>0$, $a \\ne 1$) [3.8점]",
        choices: ["$\\frac{4}{5}$", "$\\frac{5}{4}$", "$\\frac{3}{4}$", "$\\frac{3}{2}$", "$\\frac{2}{3}$"],
        answer: "②",
        solution: "1단계: $\\frac{a^x - a^{-x}}{a^x + a^{-x}} = \\frac{1}{2}$의 좌변 분모, 분자에 $a^x$를 곱하면 $\\frac{a^{2x} - 1}{a^{2x} + 1} = \\frac{1}{2}$이다.\\n2단계: 대각선으로 곱하여 정리하면 $2(a^{2x} - 1) = a^{2x} + 1 \\Rightarrow 2a^{2x} - 2 = a^{2x} + 1 \\Rightarrow a^{2x} = 3$이다.\\n3단계: 구하고자 하는 식 $\\frac{a^{2x} + a^{-2x}}{a^{2x} - a^{-2x}}$에 $a^{2x} = 3, a^{-2x} = \\frac{1}{3}$을 대입한다.\\n4단계: $\\frac{3 + \\frac{1}{3}}{3 - \\frac{1}{3}} = \\frac{\\frac{10}{3}}{\\frac{8}{3}} = \\frac{10}{8} = \\frac{5}{4}$이다.\\n* 검산: $a^{2x}$의 값을 직접 대입하여 계산한 번분수의 결과가 정확함."
    },
    {
        id: 8,
        level: "중",
        category: "로그함수의 역함수",
        originalCategory: "로그함수의 역함수",
        standardCourse: "대수",
        standardUnitKey: "H22-C-06",
        standardUnit: "로그함수",
        standardUnitOrder: 6,
        content: "함수 $f(x) = \\log_2 (x-a) + 2$의 역함수의 그래프가 점 $(a+4, a+2)$를 지날 때, $a$의 값은? (단, $a$는 상수이다.) [3.8점]",
        choices: ["-5", "-4", "-3", "-2", "-1"],
        answer: "⑤",
        solution: "1단계: 역함수가 점 $(a+4, a+2)$를 지나므로, 본래 함수 $f(x)$는 점 $(a+2, a+4)$를 지난다.\\n2단계: $f(a+2) = \\log_2(a+2-a) + 2 = \\log_2 2 + 2 = 1 + 2 = 3$이다.\\n3단계: 따라서 $a+4 = 3$이므로 $a = -1$이다.\\n* 검산: $a=-1$ 대입 시 $f(1) = 3$이 되어 역함수가 $(3, 1)$을 지남을 확인. (이는 $a+4=3, a+2=1$과 일치함)"
    },
    {
        id: 9,
        level: "중",
        category: "삼각함수의 성질",
        originalCategory: "삼각함수의 성질",
        standardCourse: "대수",
        standardUnitKey: "H22-C-10",
        standardUnit: "삼각함수의 그래프",
        standardUnitOrder: 10,
        content: "$\\theta$가 제$2$사분면의 각이고 $|\\cos\\theta - \\sin\\theta| - \\sqrt{\\cos^2\\theta} = \\frac{1}{2}$일 때, $\\cos\\theta$의 값은? [3.9점]",
        choices: ["$-\\frac{\\sqrt{3}}{2}$", "$\\frac{\\sqrt{3}}{2}$", "$-\\frac{1}{2}$", "$\\frac{1}{2}$", "$-\\frac{3}{4}$"],
        answer: "①",
        solution: "1단계: $\\theta$가 제$2$사분면의 각이므로 $\\cos\\theta < 0, \\sin\\theta > 0$이다.\\n2단계: 주어진 식에서 $\\cos\\theta - \\sin\\theta < 0$이므로 $|\\cos\\theta - \\sin\\theta| = -\\cos\\theta + \\sin\\theta$이고, $\\sqrt{\\cos^2\\theta} = |\\cos\\theta| = -\\cos\\theta$이다.\\n3단계: $(-\\cos\\theta + \\sin\\theta) - (-\\cos\\theta) = \\frac{1}{2} \\Rightarrow \\sin\\theta = \\frac{1}{2}$이다.\\n4단계: $\\cos\\theta = -\\sqrt{1 - \\sin^2\\theta} = -\\sqrt{1 - \\frac{1}{4}} = -\\frac{\\sqrt{3}}{2}$이다.\\n* 검산: $\\theta = \\frac{5\\pi}{6}$를 대입하면 식이 성립함을 확인."
    },
    {
        id: 10,
        level: "중",
        category: "로그함수의 그래프",
        originalCategory: "로그함수의 그래프",
        standardCourse: "대수",
        standardUnitKey: "H22-C-06",
        standardUnit: "로그함수",
        standardUnitOrder: 6,
        content: "함수 $y=2\\log(x+1)+1$에 대한 설명으로 옳은 것만을 <보기>\\n에서 있는대로 모두 고른 것은? [4점]\\n<보기>\\nㄱ. 그래프는 점 $(0, 1)$을 지난다.\\nㄴ. 그래프의 점근선은 직선 $y=1$이다.\\nㄷ. 그래프는 제 $4$사분면을 지나지 않는다.\\nㄹ. 그래프는 함수 $y=\\log(x+1)^2$를 $y$축의 방향으로 $1$만큼\\n    평행이동 한 것이다.",
        choices: ["ㄱ", "ㄱ, ㄷ", "ㄱ, ㄷ, ㄹ", "ㄴ, ㄹ", "ㄴ, ㄷ, ㄹ"],
        answer: "②",
        solution: "1단계: ㄱ. $x=0$을 대입하면 $y=2\\log 1+1=1$이므로 $(0, 1)$을 지난다. (참)\\n2단계: ㄴ. 로그함수의 진수 조건 $x+1>0$에 의해 점근선은 $x=-1$이다. (거짓)\\n3단계: ㄷ. $x>-1$에서 $y$값은 $-\\infty$부터 증가하며, $x=0$일 때 $y=1>0$이므로 제$4$사분면을 지나지 않는다. (참)\\n4단계: ㄹ. $y=\\log(x+1)^2$은 정의역이 $x \\ne -1$이므로 주어진 함수(정의역 $x>-1$)와 일치하지 않는다. (거짓)\\n* 검산: 옳은 것은 ㄱ, ㄷ이므로 정답은 ②번임을 확인."
    },
    {
        id: 11,
        level: "중",
        category: "지수법칙",
        originalCategory: "지수법칙",
        standardCourse: "대수",
        standardUnitKey: "H22-C-02",
        standardUnit: "지수법칙",
        standardUnitOrder: 2,
        content: "$\\sqrt[4]{\\frac{\\sqrt[3]{a^2}}{\\sqrt{a}}} \\times \\sqrt[8]{\\frac{\\sqrt[6]{a}}{a}}$ 를 간단히 하면 $\\sqrt[n]{\\frac{1}{a}}$이다. 자연수 $n$의 값\\n은? (단, $a>0$, $a \\ne 1$) [4점]",
        choices: ["12", "14", "16", "18", "20"],
        answer: "③",
        solution: "1단계: 주어진 식의 각 항을 지수 법칙을 이용해 분리한다.\\n2단계: $\\frac{a^{\\frac{2}{12}}}{a^{\\frac{1}{8}}} \\times \\frac{a^{\\frac{1}{48}}}{a^{\\frac{1}{8}}}$\\n3단계: $a^{\\frac{1}{6} - \\frac{1}{8} + \\frac{1}{48} - \\frac{1}{8}} = a^{\\frac{8 - 6 + 1 - 6}{48}} = a^{-\\frac{3}{48}} = a^{-\\frac{1}{16}}$이다.\\n4단계: $a^{-\\frac{1}{16}} = \\sqrt[16]{\\frac{1}{a}}$이므로 $n=16$이다.\\n* 검산: 지수 연산의 분모를 48로 통분하여 계산한 결과가 일치함을 확인."
    },
    {
        id: 12,
        level: "중",
        category: "동경의 위치 관계",
        originalCategory: "동경의 위치 관계",
        standardCourse: "대수",
        standardUnitKey: "H22-C-09",
        standardUnit: "삼각함수의 뜻과 값",
        standardUnitOrder: 9,
        content: "$\\frac{\\pi}{2} < \\theta < \\pi$이고 각 $\\theta$를 나타내는 동경과 각 $4\\theta$를 나타내는\\n동경이 일치할 때, 각 $\\theta = \\frac{q}{p}\\pi$이다. 서로소인 두 자연수\\n$p, q$에 대해 $p-q$의 값은? [4.1점]",
        choices: ["2", "1", "0", "-1", "-2"],
        answer: "②",
        solution: "1단계: 두 동경이 일치하므로 $4\\theta - \\theta = 2n\\pi$ ($n$은 정수)이다.\\n2단계: $3\\theta = 2n\\pi \\Rightarrow \\theta = \\frac{2n}{3}\\pi$.\\n3단계: $\\frac{\\pi}{2} < \\theta < \\pi$이므로 $\\frac{\\pi}{2} < \\frac{2n}{3}\\pi < \\pi \\Rightarrow \\frac{3}{4} < n < \\frac{3}{2}$이다.\\n4단계: 이를 만족하는 정수 $n=1$이며, $\\theta = \\frac{2}{3}\\pi$이다.\\n5단계: $p=3, q=2$이므로 $p-q=1$이다.\\n* 검산: $\\theta = \\frac{2}{3}\\pi$와 $4\\theta = \\frac{8}{3}\\pi$의 동경이 일치함을 확인."
    },
    {
        id: 13,
        level: "중",
        category: "부채꼴의 호의 길이와 넓이",
        originalCategory: "부채꼴의 호의 길이와 넓이",
        standardCourse: "대수",
        standardUnitKey: "H22-C-09",
        standardUnit: "삼각함수의 뜻과 값",
        standardUnitOrder: 9,
        content: "둘레의 길이가 $20$인 부채꼴 중에서 그 넓이가 최대인 부채\\n꼴의 넓이를 $a$, 넓이가 최대인 부채꼴의 중심각의 크기를\\n$b$라고 할 때, $a+b$의 값은? [4.2점]",
        choices: ["8", "14", "12", "25", "27"],
        answer: "⑤",
        solution: "1단계: 부채꼴의 반지름을 $r$, 호의 길이를 $l$이라 하면 $2r + l = 20$이므로 $l = 20 - 2r$이다.\\n2단계: 넓이 $S = \\frac{1}{2}rl = \\frac{1}{2}r(20-2r) = -r^2 + 10r = -(r-5)^2 + 25$이다.\\n3단계: $r=5$일 때 최대 넓이 $a=25$를 갖고, 이때 $l=10$이다.\\n4단계: 중심각 $b = \\frac{l}{r} = \\frac{10}{5} = 2$이므로 $a+b = 25+2 = 27$이다.\\n* 검산: $r=5, l=10, \\theta=2$일 때 둘레 $20$, 넓이 $25$가 성립함을 확인."
    },
    {
        id: 14,
        level: "상",
        category: "지수함수의 그래프와 방정식",
        originalCategory: "지수함수의 그래프와 방정식",
        standardCourse: "대수",
        standardUnitKey: "H22-C-03",
        standardUnit: "지수함수",
        standardUnitOrder: 3,
        content: "함수 $f(x) = \\begin{cases} |4^x - 4| & (x \\ge 0) \\\\ |4^{-x} - 4| & (x < 0) \\end{cases}$ 와 직선 $y=k$ ($k$는 실수)\\n에 대하여 방정식 $f(x)=k$이 서로 다른 세 실근을 가질\\n때, $k$의 값은? [4.2점]",
        choices: ["1", "2", "3", "4", "5"],
        answer: "③",
        solution: "1단계: $f(x)$의 그래프는 $y$축에 대해 대칭이며, $x \\ge 0$일 때 $y = |4^x - 4|$의 그래프를 그린다.\\n2단계: $x=0$에서 $y=3$이고, $x=1$에서 $y=0$이며, 점근선은 없는 형태로 증가한다.\\n3단계: $f(x)=k$가 서로 다른 세 실근을 가지려면 직선 $y=k$가 극대점인 $(0, 3)$을 지나야 한다.\\n4단계: 따라서 $k=3$이다.\\n* 검산: $k=3$일 때 $x=0$과 양수, 음수에서 각각 1개씩 총 3개의 실근을 가짐을 확인."
    },
    {
        id: 15,
        level: "중",
        category: "로그부등식과 이차방정식",
        originalCategory: "로그부등식과 이차방정식",
        standardCourse: "대수",
        standardUnitKey: "H22-C-08",
        standardUnit: "지수·로그 부등식",
        standardUnitOrder: 8,
        content: "이차방정식 $x^2 - x\\log_2 k^2 + \\log_2 k + 6 = 0$이 실근을 갖도록\\n하는 실수 $k$의 범위는? [4.3점]",
        choices: ["$0 < k \\le \\frac{1}{4}$ or $k \\ge 8$", "$k \\le \\frac{1}{4}$ or $k \\ge 8$", "$0 < k < \\frac{1}{4}$ or $k > 8$", "$k \\le \\frac{1}{8}$ or $k \\ge 4$", "$0 < k < \\frac{1}{8}$ or $k \\ge 4$"],
        answer: "①",
        solution: "1단계: 로그의 진수 조건에 의해 $k>0$이다.\\n2단계: 이차방정식이 실근을 가지려면 판별식 $D \\ge 0$이어야 한다. $D = (\\log_2 k^2)^2 - 4(\\log_2 k + 6) \\ge 0$.\\n3단계: $(2\\log_2 k)^2 - 4\\log_2 k - 24 \\ge 0 \\Rightarrow 4(\\log_2 k)^2 - 4\\log_2 k - 24 \\ge 0 \\Rightarrow (\\log_2 k)^2 - \\log_2 k - 6 \\ge 0$.\\n4단계: $(\\log_2 k - 3)(\\log_2 k + 2) \\ge 0$이므로 $\\log_2 k \\ge 3$ 또는 $\\log_2 k \\le -2$이다.\\n5단계: 따라서 $k \\ge 8$ 또는 $k \\le \\frac{1}{4}$이며, 진수 조건에 의해 $0 < k \\le \\frac{1}{4}$ 또는 $k \\ge 8$이다.\\n* 검산: $k=8$ 대입 시 $x^2 - 6x + 9 = 0$으로 중근을 가짐을 확인."
    },
    {
        id: 16,
        level: "상",
        category: "거듭제곱근의 성질",
        originalCategory: "거듭제곱근의 성질",
        standardCourse: "대수",
        standardUnitKey: "H22-C-01",
        standardUnit: "지수의 뜻과 성질",
        standardUnitOrder: 1,
        content: "$5 \\le n \\le 14$인 자연수 $n$에 대하여 $n^2 - 15n + 50$의 $n$제곱근\\n중 실수인 것의 개수를 $f(n)$이라 하자. $2f(n) = f(n+1)$을\\n만족시키는 모든 $n$의 값의 합은? [4.4점]",
        choices: ["19", "20", "22", "24", "25"],
        answer: "④",
        solution: "1단계: $n$이 홀수일 때 실수인 거듭제곱근의 개수 $f(n)$은 항상 $1$이다.\\n2단계: $n$이 짝수일 때, $n^2-15n+50 = (n-5)(n-10)$의 부호에 따라 $f(n)$은 양수면 $2$, $0$이면 $1$, 음수면 $0$이다.\\n3단계: $5 \\le n \\le 14$ 범위에서 $f(n)$의 값을 구하면 $f(6)=0, f(8)=0, f(10)=1, f(12)=2, f(14)=2$이다. (홀수는 모두 $1$)\\n4단계: $2f(n) = f(n+1)$을 만족하는 경우는 $2f(11) = 2 \\times 1 = 2 = f(12)$와 $2f(13) = 2 \\times 1 = 2 = f(14)$이다.\\n5단계: 만족하는 $n$은 $11, 13$이므로 합은 $24$이다.\\n* 검산: $n=11$과 $n=13$ 대입 시 조건식이 완벽히 성립함을 확인."
    },
    {
        id: 17,
        level: "상",
        category: "로그의 성질",
        originalCategory: "로그의 성질",
        standardCourse: "대수",
        standardUnitKey: "H22-C-05",
        standardUnit: "로그의 성질",
        standardUnitOrder: 5,
        content: "두 실수 $a, b$가 다음 <조건>을 만족시킬 때, $(\\log_a 2)^2 \\times \\log_2 b = \\frac{p}{q}$\\n이다. $p+q$ 값은? (단, $p, q$는 서로소인 자연수) [4.5점]\\n                    <조건>\\n(가) $\\log_{\\sqrt{2}} ab = 18$\\n(나) $\\log_a \\sqrt{b} = \\log_{\\sqrt{b}} a$\\n(다) $1 < a < b$",
        choices: ["5", "6", "7", "8", "9"],
        answer: "①",
        solution: "1단계: (나)에서 $\\frac{1}{2}\\log_a b = 2\\log_b a \\Rightarrow (\\log_a b)^2 = 4$이다. (다) $1<a<b$이므로 $\\log_a b = 2 \\Rightarrow b=a^2$이다.\\n2단계: (가)에서 $\\log_{\\sqrt{2}} ab = 18 \\Rightarrow ab = (\\sqrt{2})^{18} = 2^9$이다.\\n3단계: $a(a^2) = a^3 = 2^9 \\Rightarrow a=2^3=8$이고, $b=2^6=64$이다.\\n4단계: $(\\log_a 2)^2 \\times \\log_2 b = (\\log_8 2)^2 \\times \\log_2 64 = (\\frac{1}{3})^2 \\times 6 = \\frac{6}{9} = \\frac{2}{3}$이다.\\n5단계: $p=3, q=2$이므로 $p+q=5$이다.\\n* 검산: $a=8, b=64$를 각 조건에 대입하여 모순이 없음을 확인."
    },
    {
        id: 18,
        level: "상",
        category: "로그함수의 그래프",
        originalCategory: "로그함수의 그래프",
        standardCourse: "대수",
        standardUnitKey: "H22-C-06",
        standardUnit: "로그함수",
        standardUnitOrder: 6,
        content: "실수 전체 집합에서 정의된 함수 $f(x)$가 다음 조건을 만족시킨다.\\n| (가) $f(x) = \\begin{cases} x & (0 \\le x < 1) \\\\ -x+2 & (1 \\le x < 2) \\end{cases}$ |\\n| (나) 모든 실수 $x$에 대하여 $f(x+2) = f(x)$이다. |\\n자연수 $n$에 대하여 함수 $y=f(x)$의 그래프가 함수\\n$y=\\log_{3n} x$와 만나는 점의 개수가 $98$일 때, 자연수 $n$의 값\\n은? [4.6점]",
        choices: ["27", "30", "33", "36", "39"],
        answer: "③",
        solution: "1단계: 함수 $f(x)$는 주기가 $2$인 주기함수이며, 각 구간 $[2k, 2k+2]$마다 $x=2k+1$에서 최댓값 $1$을 갖는 산 모양의 그래프를 그린다.\\n2단계: 함수 $y=\\log_{3n} x$는 점 $(1, 0)$과 $(3n, 1)$을 지나는 증가함수이다.\\n3단계: 교점의 개수를 파악하기 위해 $3n$이 홀수인 경우($3n=2k+1$)를 가정한다. $y=\\log_{3n} x$가 $y=1$에 도달하는 $x=2k+1$까지 교점을 센다.\\n4단계: $x=1$에서 $1$개의 교점을 가지며, $x=3, 5, \\cdots, 2k-1$의 $k-1$개 봉우리에서는 각각 $2$개씩 교점을 갖고, 마지막 $x=2k+1$에서 꼭짓점과 $1$개의 교점을 갖는다.\\n5단계: 총 교점의 개수는 $1 + 2(k-1) + 1 = 2k$이다. (만약 $3n$이 짝수라면 총 교점은 홀수개가 되어 $98$개가 될 수 없다.)\\n6단계: $2k = 98$이므로 $k=49$이다. 따라서 $3n = 2(49) + 1 = 99$이므로 $n=33$이다.\\n* 검산: $n=33$일 때 $y=\\log_{99} x$는 $(99, 1)$을 지나며, 이때 산 모양 그래프의 $49$번째 봉우리까지 좌우로 두 번씩 만나고 $50$번째 꼭짓점에서 한 번 만나 정확히 $98$개의 교점을 갖는다."
    },
    {
        id: 19,
        level: "상",
        category: "지수함수와 로그함수의 그래프",
        originalCategory: "지수함수와 로그함수의 그래프",
        standardCourse: "대수",
        standardUnitKey: "H22-C-06",
        standardUnit: "로그함수",
        standardUnitOrder: 6,
        content: "두 양수 $a, b(a>1, 0<b<1)$에 대하여\\n$f(x) = \\begin{cases} \\log_2 (x-4) - a & (x \\ge 6) \\\\ b^{x-6} - a & (x < 6) \\end{cases}$ 이다. 함수 $y=f(x)$와 $x$축\\n이 만나는 두 점을 각각 $\\mathrm{A, B}$라 하자. $\\overline{\\mathrm{AB}} = 5$ 이고\\n$f(12) = \\frac{a}{2}$일 때, $(ab)^3$의 값은? [4.6점]",
        choices: ["$\\frac{1}{2}$", "4", "8", "12", "27"],
        answer: "②",
        solution: "1단계: $f(12) = \\frac{a}{2}$를 이용해 $a$를 구한다. $12 \\ge 6$이므로 $f(12) = \\log_2 (12-4) - a = \\log_2 8 - a = 3 - a$이다.\\n2단계: $3 - a = \\frac{a}{2} \\Rightarrow \\frac{3a}{2} = 3 \\Rightarrow a = 2$이다.\\n3단계: 함수 $f(x)$와 $x$축이 만나는 점은 $f(x)=0$의 해이다. $x \\ge 6$일 때 $\\log_2 (x-4) - 2 = 0 \\Rightarrow x-4 = 2^2 \\Rightarrow x=8$이다. (점 $\\mathrm{A}$를 $(8, 0)$이라 하자.)\\n4단계: $\\overline{\\mathrm{AB}} = 5$이므로 점 $\\mathrm{B}$의 $x$좌표는 $8-5=3$ 또는 $8+5=13$이다. $13$은 $x \\ge 6$ 구간의 유일한 해가 $8$임에 모순되므로, 나머지 한 해는 $x < 6$ 구간에 속하는 $x=3$이다.\\n5단계: $f(3) = 0$을 이용해 $b$를 구한다. $b^{3-6} - 2 = 0 \\Rightarrow b^{-3} = 2 \\Rightarrow b^3 = \\frac{1}{2}$이다.\\n6단계: $(ab)^3 = a^3b^3 = 2^3 \\times \\frac{1}{2} = 4$이다.\\n* 검산: $a=2, b=2^{-1/3}$을 대입하여 $(ab)^3$을 계산한 결과가 4로 정확히 일치함."
    },
    {
        id: 20,
        level: "최상",
        category: "지수함수의 그래프",
        originalCategory: "지수함수의 그래프",
        standardCourse: "대수",
        standardUnitKey: "H22-C-03",
        standardUnit: "지수함수",
        standardUnitOrder: 3,
        content: "두 상수 $a, k(1 < a < 3, 0 < k < 1)$에 대하여 직선 $y=3$이\\n두 곡선 $y=3^{x+1}$, $y=a^{x+1}$과 만나는 두 점을 각각 $\\mathrm{A, B}$\\n라 하고, 직선 $y=k$가 두 곡선 $y=3^{x+1}$, $y=a^{x+1}$과 만나\\n는 두 점을 각각 $\\mathrm{C, D}$라 하자. 사각형 $\\mathrm{ADCB}$가 넓이가\\n$\\frac{8}{3}$인 평행사변형일 때, $ak$의 값은? [4.7점]",
        choices: ["$3^{\\frac{1}{3}}$", "$3^{-\\frac{1}{3}}$", "$3^{\\frac{1}{2}}$", "$3^{-\\frac{1}{2}}$", "$3^{\\frac{3}{2}}$"],
        answer: "④",
        solution: "1단계: 각 점의 좌표를 구한다. $y=3$과의 교점: $\\mathrm{A}(0, 3)$, $\\mathrm{B}(\\log_a 3 - 1, 3)$. $y=k$와의 교점: $\\mathrm{C}(\\log_3 k - 1, k)$, $\\mathrm{D}(\\log_a k - 1, k)$. (단, $1<a<3$이고 $0<k<1$이므로 $\\log_a k < \\log_3 k$가 되어 점 $\\mathrm{D}$가 점 $\\mathrm{C}$의 왼쪽에 위치한다.)\\n2단계: 사각형 $\\mathrm{ADCB}$가 평행사변형이므로 $\\vec{AD} = \\vec{BC}$이다. $\\log_a k - 1 = \\log_3 k - 1 - (\\log_a 3 - 1)$이 성립한다.\\n3단계: $\\log_a k = \\log_3 k - \\log_a 3 + 1$. 밑을 $3$으로 통일하면 $\\frac{\\log_3 k}{\\log_3 a} = \\log_3 k - \\frac{1}{\\log_3 a} + 1$이다.\\n4단계: $\\log_3 a = u, \\log_3 k = v$라 치환하면 $\\frac{v}{u} = v - \\frac{1}{u} + 1 \\Rightarrow v = uv - 1 + u \\Rightarrow uv - v + u - 1 = 0 \\Rightarrow (u-1)(v+1)=0$이다. $1<a<3$이므로 $u \\ne 1$이고, 따라서 $v = -1$이 되어 $k = 3^{-1} = \\frac{1}{3}$이다.\\n5단계: 평행사변형의 넓이는 $(\\text{밑변}) \\times (\\text{높이}) = \\overline{\\mathrm{AB}} \\times (3 - k) = (\\log_a 3 - 1) \\times (3 - \\frac{1}{3}) = (\\log_a 3 - 1) \\times \\frac{8}{3} = \\frac{8}{3}$이다.\\n6단계: $\\log_a 3 - 1 = 1 \\Rightarrow \\log_a 3 = 2 \\Rightarrow a^2 = 3 \\Rightarrow a = 3^{\\frac{1}{2}}$이다.\\n7단계: $ak = 3^{\\frac{1}{2}} \\times 3^{-1} = 3^{-\\frac{1}{2}}$이다.\\n* 검산: $a=\\sqrt{3}, k=\\frac{1}{3}$을 대입하여 네 점의 좌표를 구해 벡터와 넓이를 확인한 결과 조건과 완벽히 일치함."
    },
    {
        id: "서술형1",
        level: "중",
        category: "지수함수의 최대·최소",
        originalCategory: "지수함수의 최대·최소",
        standardCourse: "대수",
        standardUnitKey: "H22-C-03",
        standardUnit: "지수함수",
        standardUnitOrder: 3,
        content: "정의역이 $\\{x | x \\le 2\\}$인 함수 $y = 2^{2x} - 2^{x+1} - 8$은 $x=a$일 때 최\\n댓값 $M$을 갖고 $x=b$일 때 최솟값 $m$을 갖는다. 실수\\n$a, b, M, m$을 구하는 과정과 정답을 서술하시오. [6점]",
        choices: [],
        answer: "a=2, b=0, M=0, m=-9",
        solution: "1단계: $2^x = t$로 치환한다. $x \\le 2$이므로 $t$의 범위는 $0 < t \\le 4$이다.\\n2단계: 주어진 함수를 $t$에 대한 이차함수로 나타내면 $y = t^2 - 2t - 8 = (t-1)^2 - 9$이다.\\n3단계: 대칭축이 $t=1$이고 범위가 $0 < t \\le 4$이므로, $t=1$일 때 최솟값을 갖고, 대칭축에서 가장 먼 $t=4$일 때 최댓값을 갖는다.\\n4단계: $t=1$일 때 $y = -9$이므로 $m = -9$이다. 이때 $2^x = 1$이므로 $x=0$이 되어 $b=0$이다.\\n5단계: $t=4$일 때 $y = (4-1)^2 - 9 = 0$이므로 $M = 0$이다. 이때 $2^x = 4$이므로 $x=2$가 되어 $a=2$이다.\\n* 검산: 원함수 양 끝값 및 극값 대입 비교 ($x=2 \\rightarrow y=0$, $x=0 \\rightarrow y=-9$, $x \\rightarrow -\\infty \\rightarrow y=-8$) 결과 이상 없음."
    },
    {
        id: "서술형2",
        level: "중",
        category: "상용로그의 활용",
        originalCategory: "상용로그의 활용",
        standardCourse: "대수",
        standardUnitKey: "H22-C-05",
        standardUnit: "로그의 성질",
        standardUnitOrder: 5,
        content: "빛이 어떤 유리판을 한 장 통과할 때마다 그 밝기가 $5\\%$씩 감소\\n한다고 한다. 밝기가 $A$인 빛이 이 유리판을 $20$장 통과했을 때\\n그 밝기는 처음의 몇 배가 되는지 구하는 과정과 정답을 서술하시\\n오. (단, $\\log 9.5 = 0.9777$, $\\log 3.581 = 0.5540$으로 계산한다.) [7점]",
        choices: [],
        answer: "0.3581",
        solution: "1단계: $20$장 통과 후의 밝기는 $A(1 - 0.05)^{20} = A(0.95)^{20}$이다. 처음 밝기의 $x$배가 된다고 하면 $x = 0.95^{20}$이다.\\n2단계: 양변에 상용로그를 취하면 $\\log x = 20\\log 0.95$이다.\\n3단계: $\\log 0.95 = \\log (9.5 \\times 10^{-1}) = \\log 9.5 - 1 = 0.9777 - 1 = -0.0223$이다.\\n4단계: $\\log x = 20 \\times (-0.0223) = -0.446$이다.\\n5단계: 상용로그표를 이용하기 위해 소수 부분을 양수로 바꾸면 $-0.446 = -1 + 0.554$이다.\\n6단계: 주어진 조건에 의해 $0.554 = \\log 3.581$이므로, $\\log x = -1 + \\log 3.581 = \\log(3.581 \\times 10^{-1}) = \\log 0.3581$이다.\\n7단계: 따라서 $x = 0.3581$이므로 $0.3581$배이다.\\n* 검산: 역산하여 $\\log 0.3581 / 20 = -0.0223$이 도출됨을 확인."
    },
    {
        id: "서술형3",
        level: "상",
        category: "로그의 성질",
        originalCategory: "로그의 성질",
        standardCourse: "대수",
        standardUnitKey: "H22-C-05",
        standardUnit: "로그의 성질",
        standardUnitOrder: 5,
        content: "$1$이 아닌 세 양수 $a, b, c$가 $-5\\log_a b = 25\\log_b c = \\log_c a$ 를 만\\n족시킨다. $b \\times c$의 값이 $200$ 이하의 자연수가 되도록 하는 모든\\n자연수 $a$의 값의 합을 구하는 과정과 정답을 서술하시오. [7점]",
        choices: [],
        answer: "275",
        solution: "1단계: $-5\\log_a b = 25\\log_b c = \\log_c a = k$라 둔다.\\n2단계: $\\log_a b = -\\frac{k}{5}$, $\\log_b c = \\frac{k}{25}$, $\\log_c a = k$이다.\\n3단계: 로그의 성질에 의해 $\\log_a b \\times \\log_b c \\times \\log_c a = 1$이므로, $(-\\frac{k}{5}) \\times (\\frac{k}{25}) \\times k = 1 \\Rightarrow -\\frac{k^3}{125} = 1 \\Rightarrow k^3 = -125 \\Rightarrow k = -5$이다.\\n4단계: 대입하면 $\\log_a b = 1 \\Rightarrow b = a$이고, $\\log_b c = -\\frac{1}{5} \\Rightarrow c = b^{-\\frac{1}{5}} = a^{-\\frac{1}{5}}$이다.\\n5단계: $b \\times c = a \\times a^{-\\frac{1}{5}} = a^{\\frac{4}{5}}$이다. 이 값이 자연수가 되려면 $a$는 어떤 자연수 $m$의 $5$제곱 형태인 $m^5$이어야 한다. (단, $a \\ne 1$이므로 $m \\ge 2$)\\n6단계: $a = m^5$일 때 $b \\times c = (m^5)^{\\frac{4}{5}} = m^4$이다.\\n7단계: $m^4 \\le 200$을 만족하는 자연수 $m$은 $m=2$ ($2^4=16$), $m=3$ ($3^4=81$)이다.\\n8단계: $m=2$일 때 $a = 2^5 = 32$, $m=3$일 때 $a = 3^5 = 243$이다. 따라서 모든 $a$의 합은 $32 + 243 = 275$이다.\\n* 검산: $a=32, b=32, c=1/2$일 때 주어진 비례식이 성립하며 곱이 $16$으로 $200$ 이하 조건을 충족함을 확인. $a=243$일 때도 동일하게 성립."
    }
];