/**
 * 2025학년도 순천팔마고등학교 1학년 1학기 중간고사 수학 데이터베이스
 * 제작자: AP수학학원 조수 제미나이
 * 엔진 버전: v6.5.4 [IRONCLAD] (Logical Anchor Edition)
 */

window.examTitle = "25_팔마고1_1학기_중간_고1_기출";

window.questionBank = [
  {
    "id": 1,
    "level": "하",
    "category": "나머지 정리",
    "originalCategory": "나머지 정리",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-02",
    "standardUnit": "항등식과 나머지정리",
    "standardUnitOrder": 2,
    "content": "다항식 $P(x)=x^{3}-x^{2}+kx+6$이 $x-2$로 나누어떨어질 때, 실수 $k$의 값을 구하시오. [3.5점]",
    "choices": ["$-5$", "$-3$", "$-1$", "$1$", "$3$"],
    "answer": "①",
    "solution": "$P(2)=0 \\implies 8-4+2k+6=0 \\implies 2k+10=0 \\implies k=-5$"
  },
  {
    "id": 2,
    "level": "하",
    "category": "곱셈 공식",
    "originalCategory": "곱셈 공식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-01",
    "standardUnit": "다항식의 연산",
    "standardUnitOrder": 1,
    "content": "두 다항식을 인수분해 하여 $a^{2}+b^{2}+c^{2}+2ab+2bc+2ca=A^{2}, a^{3}-3a^{2}b+3ab^{2}-b^{3}=B^{3}$일 때, $A+B$를 구하시오. (단, 다항식 $A$는 $a$의 계수가 양수인 $a, b, c$에 대한 일차식이고, 다항식 $B$는 $a, b$에 대한 일차식이다.) [3.5점]",
    "choices": ["$c$", "$2a+c$", "$2b+c$", "$2a+b+c$", "$2a+2b+c$"],
    "answer": "②",
    "solution": "$a^2+b^2+c^2+2ab+2bc+2ca=(a+b+c)^2 \\implies A=a+b+c$\n$a^3-3a^2b+3ab^2-b^3=(a-b)^3 \\implies B=a-b$\n$\\therefore A+B=(a+b+c)+(a-b)=2a+c$"
  },
  {
    "id": 3,
    "level": "하",
    "category": "이차방정식의 판별식",
    "originalCategory": "이차방정식의 판별식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-05",
    "standardUnit": "이차방정식",
    "standardUnitOrder": 5,
    "content": "이차방정식 $x^{2}+2x+k-4=0$이 서로 다른 두 허근을 가질 때, 정수 $k$의 최솟값을 구하시오. [3.5점]",
    "choices": ["$2$", "$3$", "$4$", "$5$", "$6$"],
    "answer": "⑤",
    "solution": "$D<0 \\implies 2^2-4(k-4)<0 \\implies 4-4k+16<0 \\implies 20-4k<0 \\implies k>5$\n$\\therefore \\text{최솟값 }6$"
  },
  {
    "id": 4,
    "level": "하",
    "category": "다항식의 나눗셈",
    "originalCategory": "다항식의 나눗셈",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-01",
    "standardUnit": "다항식의 연산",
    "standardUnitOrder": 1,
    "content": "다항식 $2x^{3}+3x^{2}-4x+11$을 $x^{2}-x+2$로 나누었을 때 몫과 나머지가 옳게 짝지어진 것을 고르시오. [3.7점]",
    "choices": ["몫: $2x+1$, 나머지: $-x+13$", "몫: $2x+1$, 나머지: $x+9$", "몫: $2x+5$, 나머지: $-3x+1$", "몫: $2x+5$, 나머지: $-11x+22$", "몫: $2x+9$, 나머지: $x-8$"],
    "answer": "③",
    "solution": "$2x^3+3x^2-4x+11 \\div (x^2-x+2)$\n$=2x+5, \\text{ 나머지 }-3x+1$\n$\\therefore ③$"
  },
  {
    "id": 5,
    "level": "하",
    "category": "복소수의 연산",
    "originalCategory": "복소수의 연산",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-04",
    "standardUnit": "복소수",
    "standardUnitOrder": 4,
    "content": "두 실수 $x, y$에 대하여 $i(2+xi)+(3-yi)=1+2i$일 때, $x+y$의 값을 구하시오. (단, $i=\\sqrt{-1}$이다) [3.7점]",
    "choices": ["$-5$", "$-2$", "$0$", "$2$", "$5$"],
    "answer": "④",
    "solution": "$i(2+xi)=2i+xi^2=2i-x$\n$(3-yi)=3-yi$\n$\\implies (3-x)+(2-y)i=1+2i$\n$\\implies 3-x=1,\\;2-y=2$\n$\\implies x=2,\\;y=0$\n$\\therefore x+y=2$"
  },
  {
    "id": 6,
    "level": "하",
    "category": "이차방정식의 근과 계수",
    "originalCategory": "이차방정식의 근과 계수",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-05",
    "standardUnit": "이차방정식",
    "standardUnitOrder": 5,
    "content": "이차방정식 $x^{2}+5x-7=0$의 두 근을 $\\alpha, \\beta$라 할 때, $\\alpha^{2}\\beta+\\alpha\\beta^{2}$의 값을 구하시오. [3.7점]",
    "choices": ["$-35$", "$-7$", "$-5$", "$5$", "$35$"],
    "answer": "⑤",
    "solution": "$\\alpha+\\beta=-5, \\alpha\\beta=-7$\n$\\alpha^2\\beta+\\alpha\\beta^2=\\alpha\\beta(\\alpha+\\beta)$\n$=(-7)(-5)=35$"
  },
  {
    "id": 7,
    "level": "중",
    "category": "다항식의 인수분해",
    "originalCategory": "다항식의 인수분해",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "다음 중 다항식 $(x^{2}+4x+1)(x^{2}+4x+2)-6$을 인수분해한 것으로 옳은 것을 고르시오. [4점]",
    "choices": ["$(x+2)^{2}(x^{2}+4x-1)$", "$(x+2)^{2}(x^{2}+4x+1)$", "$(x-1)(x+1)(x+2)^{2}$", "$(x^{2}+4x+1)(x^{2}+4x-1)$", "$(x-1)(x+5)(x^{2}+4x-1)$"],
    "answer": "①",
    "solution": "$t=x^2+4x \\implies (t+1)(t+2)-6=t^2+3t-4=(t+4)(t-1)=(x^2+4x+4)(x^2+4x-1)=(x+2)^2(x^2+4x-1)$"
  },
  {
    "id": 8,
    "level": "중",
    "category": "이차함수와 직선",
    "originalCategory": "이차함수와 직선",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-13",
    "standardUnit": "이차함수",
    "standardUnitOrder": 13,
    "content": "이차함수 $y=3x^{2}-4x-7$의 그래프와 직선 $y=10x+10$의 그래프의 두 교점의 $x$좌표를 각각 $a, b$라 하자. $a+b$의 값이 $\\frac{\\beta}{\\alpha}$일 때, $\\alpha+\\beta$의 값을 구하시오. (단, $a, b$는 실수이고, $\\alpha$와 $\\beta$는 서로소인 자연수이다.) [4점]",
    "choices": ["$7$", "$11$", "$13$", "$17$", "$20$"],
    "answer": "④",
    "solution": "$3x^2-4x-7=10x+10 \\implies 3x^2-14x-17=0 \\implies a+b=\\frac{14}{3} \\therefore \\alpha=3,\\;\\beta=14 \\implies \\alpha+\\beta=17$"
  },
  {
    "id": 9,
    "level": "중",
    "category": "항등식",
    "originalCategory": "항등식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-02",
    "standardUnit": "항등식과 나머지정리",
    "standardUnitOrder": 2,
    "content": "등식 $y=2x+2k$를 만족시키는 모든 실수 $x, y$에 대하여 등식 $ax^{2}+xy+3y+18=0$이 항상 성립할 때, $ak$의 값을 구하시오. (단, $a, k$는 실수이다.) [4점]",
    "choices": ["$-18$", "$-6$", "$0$", "$6$", "$18$"],
    "answer": "④",
    "solution": "$y=2x+2k$ 대입\n$ax^2+x(2x+2k)+3(2x+2k)+18=0$\n$(a+2)x^2+(2k+6)x+(6k+18)=0$\n$\\implies a+2=0,\\;2k+6=0,\\;6k+18=0$\n$\\implies a=-2,\\;k=-3 \\therefore ak=6$"
  },
  {
    "id": 10,
    "level": "중",
    "category": "이차방정식의 판별식",
    "originalCategory": "이차방정식의 판별식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-05",
    "standardUnit": "이차방정식",
    "standardUnitOrder": 5,
    "content": "이차방정식 $(x^{2}+2x+3)k+3x^{2}-4x-1=0$이 중근을 갖도록 하는 모든 실수 $k$의 값의 합을 구하시오. [4.3점]",
    "choices": ["$-12$", "$-7$", "$-6$", "$6$", "$12$"],
    "answer": "③",
    "solution": "$(k+3)x^2+(2k-4)x+(3k-1)=0$\n$D=0$\n$(2k-4)^2-4(k+3)(3k-1)=0$\n$4(k-2)^2-4(3k^2+8k-3)=0$\n$(k-2)^2-(3k^2+8k-3)=0$\n$k^2-4k+4-3k^2-8k+3=0$\n$-2k^2-12k+7=0 \\therefore k_1+k_2=-\\frac{-12}{2}=-6$"
  },
  {
    "id": 11,
    "level": "상",
    "category": "복소수의 성질",
    "originalCategory": "복소수의 성질",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-04",
    "standardUnit": "복소수",
    "standardUnitOrder": 4,
    "content": "삼차방정식 $x^{3}=1$의 한 허근을 $\\omega$라 할 때, $\\frac{\\omega^{2}+\\bar{\\omega}^{2}}{1+\\omega^{2}}+\\frac{\\omega+\\bar{\\omega}}{1+\\omega}$의 값을 구하시오. (단, $\\bar{\\omega}$는 $\\omega$의 켤레복소수이다.) [4.3점]",
    "choices": ["$-2$", "$-1$", "$0$", "$1$", "$2$"],
    "answer": "②",
    "solution": "$\\omega^2+\\omega+1=0$\n$\\omega+\\bar{\\omega}=-1,\\;\\omega\\bar{\\omega}=1$\n$\\omega^2+\\bar{\\omega}^2=(\\omega+\\bar{\\omega})^2-2\\omega\\bar{\\omega}=1-2=-1$\n$\\omega^2+\\omega+1=0 \\implies 1+\\omega^2=-\\omega,\\;1+\\omega=-\\omega^2$\n$\\implies \\frac{-1}{-\\omega}+\\frac{-1}{-\\omega^2}=\\frac{1}{\\omega}+\\frac{1}{\\omega^2}$\n$=\\frac{\\omega+1}{\\omega^2}=-1$"
  },
  {
    "id": 12,
    "level": "상",
    "category": "연립방정식",
    "originalCategory": "연립방정식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-07",
    "standardUnit": "여러 가지 방정식",
    "standardUnitOrder": 7,
    "content": "연립방정식 $\\begin{cases} xy=2 \\\\ x+y+2xy=10 \\end{cases}$을 만족하는 두 실수 $x, y$에 대하여 $2x-y$의 최솟값을 구하시오. [4.3점]",
    "choices": ["$3-3\\sqrt{7}$", "$-2\\sqrt{7}$", "$6$", "$3+3\\sqrt{7}$", "$2\\sqrt{7}$"],
    "answer": "①",
    "solution": "$xy=2,\\;x+y+4=10 \\implies x+y=6$\n$t^2-6t+2=0 \\implies t=3\\pm\\sqrt{7}$\n$x,y \\in \\{3\\pm\\sqrt{7}\\}$\n$2x-y \\text{ 최소} \\Rightarrow x=3-\\sqrt{7},\\;y=3+\\sqrt{7}$\n$=2(3-\\sqrt{7})-(3+\\sqrt{7})=3-3\\sqrt{7}$"
  },
  {
    "id": 13,
    "level": "상",
    "category": "나머지 정리",
    "originalCategory": "나머지 정리",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-02",
    "standardUnit": "항등식과 나머지정리",
    "standardUnitOrder": 2,
    "content": "최고차항의 계수가 1인 삼차식 $P(x)$가 다음 <조건>을 모두 만족할 때, $P(2)$의 값을 구하시오. [4.5점]\n<div class='box'>\n<조건>\nㄱ. $P(x)$를 $x-1$로 나누었을 때 몫이 $Q(x)$, 나머지는 3이다.\nㄴ. $Q(x)$를 $(x+1)^{2}$으로 나누었을 때 나머지는 $-2$이다.\n</div>",
    "choices": ["$-10$", "$-5$", "$0$", "$5$", "$10$"],
    "answer": "⑤",
    "solution": "$P(x)=(x-1)Q(x)+3$이고 $Q(x)$는 계수가 1인 이차식이므로 $Q(x)=(x+1)^2-2$가 된다. 즉 $Q(x)=x^2+2x-1$이다. 따라서 $P(x)=(x-1)(x^2+2x-1)+3$이며, $x=2$를 대입하면 $P(2)=(1)(4+4-1)+3=10$이다."
  },
  {
    "id": 14,
    "level": "중",
    "category": "복소수의 주기성",
    "originalCategory": "복소수의 주기성",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-04",
    "standardUnit": "복소수",
    "standardUnitOrder": 4,
    "content": "복소수 $z=\\frac{\\sqrt{2}}{1+i}$에 대하여, $1+z+z^{2}+\\dots+z^{21}+z^{24}$의 값을 구하시오. (단, $i=\\sqrt{-1}$) [4.5점]",
    "choices": ["$0$", "$1$", "$2$", "$3$", "$4$"],
    "answer": "②",
    "solution": "$z=\\frac{\\sqrt{2}}{1+i}=\\frac{1-i}{\\sqrt{2}}$\n$z^2=-i,\\;z^4=-1,\\;z^8=1$\n$\\sum_{k=0}^{7}z^k=0$\n$\\sum_{k=0}^{23}z^k=0$\n$\\therefore 1+z+\\cdots+z^{21}+z^{24}=z^{24}=(z^8)^3=1$"
  },
  {
    "id": 15,
    "level": "상",
    "category": "이차함수와 판별식",
    "originalCategory": "이차함수와 판별식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-13",
    "standardUnit": "이차함수",
    "standardUnitOrder": 13,
    "content": "이차방정식 $-x^{2}+ax+b=0$의 한 근이 $1+2i$일 때, 이차함수 $y=x^{2}-2bx-a+k$는 $x$축과 접한다. $x$축과의 교점의 $x$좌표를 $\\alpha$라고 할 때, $k+4\\alpha$의 값을 구하시오. (단, $i=\\sqrt{-1}$이고, $a, b, k, \\alpha$는 실수) [4.5점]",
    "choices": ["$-5$", "$-1$", "$3$", "$7$", "$11$"],
    "answer": "④",
    "solution": "주어진 방정식의 한 근이 $1+2i$이므로 켤레근 $1-2i$도 근이다.\n$-x^2+ax+b=0 \\Rightarrow x^2-ax-b=0$\n따라서 근과 계수의 관계에 의해\n$\\alpha+\\beta=a,\\;\\alpha\\beta=-b$\n$\\alpha+\\beta=2,\\;\\alpha\\beta=5$\n$\\therefore a=2,\\;b=-5$\n\n이차함수\n$y=x^2-2bx-a+k=x^2+10x-2+k$\n\n$x$축과 접하므로 중근을 갖는다.\n$\\therefore D=0$\n$10^2-4(1)(-2+k)=0$\n$100-4k+8=0$\n$108-4k=0 \\Rightarrow k=27$\n\n$y=(x+5)^2 \\Rightarrow \\alpha=-5$\n\n$\\therefore k+4\\alpha=27+4(-5)=7$"
  },
  {
    "id": 16,
    "level": "상",
    "category": "이차방정식의 판별식",
    "originalCategory": "이차방정식의 판별식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-05",
    "standardUnit": "이차방정식",
    "standardUnitOrder": 5,
    "content": "$-20$부터 $20$까지의 정수가 각각 적혀 있는 카드 41장 중에서 카드를 한 장씩 두 번 뽑아 첫 번째, 두 번째 뽑은 카드에 적혀 있는 정수를 각각 $m, n$이라고 하자. 다음 <조건>을 모두 만족하는 순서쌍 $(m, n)$의 개수를 구하시오. (단, 뽑은 카드는 다시 뽑을 수 있다.) [4.8점]\n<div class='box'>\n<조건>\nㄱ. $x^{2}+mx+n=0$은 중근을 갖는다.\nㄴ. $x^{2}+nx+m=0$은 서로 다른 두 실근을 갖는다.\n</div>",
    "choices": ["$4$개", "$5$개", "$6$개", "$7$개", "$8$개"],
    "answer": "③",
    "solution": "중근 조건\n$m^2-4n=0 \\implies n=\\frac{m^2}{4}$\n$n$이 정수이므로 $m=2k$\n$\\therefore n=k^2$\n\n두 번째 방정식\n$x^2+k^2x+2k=0$\n서로 다른 두 실근\n$D>0$\n$k^4-8k>0$\n$k(k^3-8)>0$\n\n범위 $-20\\le m,n\\le20$\n$m=2k \\Rightarrow |k|\\le10$\n$n=k^2\\le20 \\Rightarrow |k|\\le4$\n\n따라서 $k=-4,-3,-2,-1,1,2,3,4$\n이 중 $k(k^3-8)>0$ 만족\n$k=-4,-3,-2,-1,3,4$\n\n각각 하나씩 대응\n$\\therefore 6\\text{개}$"
  },
  {
    "id": 17,
    "level": "고1",
    "category": "공통수학1",
    "originalCategory": "공통수학1",
    "standardCourse": "수학(상)",
    "standardUnitKey": "RAW-공통수학1",
    "standardUnit": "공통수학1",
    "standardUnitOrder": 999,
    "content": "오른쪽 그림과 같이 $\\overline{AB}=\\overline{AC}$인 이등변삼각형 $ABC$의 내부에 직사각형을 딱 맞게 넣으려고 한다. 삼각형 $ABC$의 넓이가 $6$이고 $\\overline{BC}=4$일 때, 이 직사각형의 넓이의 최댓값을 구하시오. [4.8점]\n<div class=\"svg-container\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 240 200\" preserveAspectRatio=\"xMidYMid meet\"><rect x=\"80\" y=\"110.0\" width=\"80\" height=\"60.0\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/><polygon points=\"120,50 40,170 200,170\" fill=\"none\" stroke=\"black\" stroke-width=\"2.5\"/><text x=\"115\" y=\"40\" font-size=\"14\" font-weight=\"bold\">A</text><text x=\"25\" y=\"175\" font-size=\"14\" font-weight=\"bold\">B</text><text x=\"205\" y=\"175\" font-size=\"14\" font-weight=\"bold\">C</text></svg></div>",
    "choices": ["3", "6", "9", "12", "15"],
    "answer": "①",
    "solution": "삼각형의 밑변을 $BC$, 높이를 $AH$라 하면 넓이가 $6$이므로 $\\frac{1}{2} \\cdot 4 \\cdot AH = 6$에서 $AH=3$이다. 직사각형의 높이를 $h$, 가로 길이를 $w$라 하면 삼각형의 닮음에 의해 $(3-h):3 = w:4$이 성립한다. 즉, $w = \\frac{4}{3}(3-h)$이다. 직사각형의 넓이 $S = w \\cdot h = \\frac{4}{3}(3-h)h$이다. $S = -\\frac{4}{3}(h-1.5)^2 + 3$이므로 $h=1.5$일 때 최댓값 $3$을 갖는다.\n<div class=\"svg-container\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 240 200\" preserveAspectRatio=\"xMidYMid meet\"><rect width=\"240\" height=\"200\" fill=\"#f9f9f9\" stroke=\"#eee\" stroke-width=\"1\"/><line x1=\"120\" y1=\"50\" x2=\"120\" y2=\"170\" stroke=\"black\" stroke-width=\"1\" stroke-dasharray=\"3 3\"/><text x=\"125\" y=\"110.0\" font-size=\"12\" font-weight=\"bold\">3</text><text x=\"115\" y=\"185\" font-size=\"12\">H</text><rect x=\"80\" y=\"110.0\" width=\"80\" height=\"60.0\" fill=\"none\" stroke=\"black\" stroke-width=\"2\"/><polygon points=\"120,50 40,170 200,170\" fill=\"none\" stroke=\"black\" stroke-width=\"2.5\"/><text x=\"115\" y=\"40\" font-size=\"14\" font-weight=\"bold\">A</text><text x=\"25\" y=\"175\" font-size=\"14\" font-weight=\"bold\">B</text><text x=\"205\" y=\"175\" font-size=\"14\" font-weight=\"bold\">C</text><text x=\"120\" y=\"188\" font-size=\"12\" text-anchor=\"middle\">4</text><text x=\"120\" y=\"105.0\" font-size=\"12\" text-anchor=\"middle\">w</text><text x=\"65\" y=\"140.0\" font-size=\"12\">h</text></svg></div>"
  },
  {
    "id": 18,
    "level": "상",
    "category": "다항식의 항등식",
    "originalCategory": "다항식의 항등식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-02",
    "standardUnit": "항등식과 나머지정리",
    "standardUnitOrder": 2,
    "content": "다항식 $P(x)$와 최고차항의 계수가 1인 이차식 $Q(x)$가 모든 실수 $x$에 대하여 $Q(x)^{2}+Q(x+2)^{2}=xP(x)$를 만족한다. $P(x)$를 $Q(x+2)$로 나누었을 때 나머지를 $R(x)$라 할 때, $R(1)$의 값을 구하시오. (단, 다항식 $P(x)$와 $Q(x)$의 계수는 모두 실수이다.) [5.2점]",
    "choices": ["$-8$", "$-2$", "$4$", "$10$", "$16$"],
    "answer": "⑤",
    "solution": "$x=0$ 대입\n$Q(0)^2+Q(2)^2=0 \\implies Q(0)=0,\\;Q(2)=0$\n이차식이므로\n$Q(x)=x(x-2)$\n원식에 대입\n$xP(x)=x^2(x-2)^2+x^2(x+2)^2$\n$=x^2[(x-2)^2+(x+2)^2]$\n$=x^2(2x^2+8)$\n$\\therefore P(x)=2x^3+8x$\n$Q(x+2)=x(x+2)$\n나머지는 1차식 $R(x)=ax+b$\n$x=0,-2$ 대입\n$P(0)=0,\\;P(-2)=-32$\n$R(0)=0,\\;R(-2)=-32$\n$\\therefore R(x)=16x \\implies R(1)=16$"
  },
  {
    "id": 19,
    "level": "상",
    "category": "복소수의 연산",
    "originalCategory": "복소수의 연산",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-04",
    "standardUnit": "복소수",
    "standardUnitOrder": 4,
    "content": "$10 \\le n \\le 100$인 자연수 $n$에 대하여 $z=\\frac{1}{\\sqrt{5}(1-\\sqrt{3}i)}$일 때, $z^n$이 유리수가 되는 $n$의 개수를 $a$, $z^n$이 유리수가 되는 $n$ 중 $10^{-8} < z^n\\overline{z^n} < 10^{-2}$가 되는 $n$의 개수를 $b$라 할 때, $a-b$의 값을 구하시오. (단, $a, b$는 자연수이다.) [5.2점]",
    "choices": ["$-3$", "$0$", "$3$", "$6$", "$9$"],
    "answer": "③",
    "solution": "$z=\\frac{1}{\\sqrt{5}(1-\\sqrt{3}i)}=\\frac{1+\\sqrt{3}i}{4\\sqrt{5}}$이므로 $z^n=\\frac{(1+\\sqrt{3}i)^n}{(4\\sqrt{5})^n}$이다. $(1+\\sqrt{3}i)^3=-8$이므로 $(1+\\sqrt{3}i)^n$이 실수가 되려면 $n$은 $3$의 배수이고, $z^n$이 유리수가 되려면 분모의 $(\\sqrt{5})^n$이 없어져야 하므로 $n$은 짝수여야 한다. 따라서 $n$은 $6$의 배수이다. $10\\le n\\le100$에서 $n=12,18,24,\\cdots,96$이므로 $a=15$이다. 또 $z^n\\overline{z^n}=(z\\overline{z})^n$이고 $z\\overline{z}=\\frac{(1+\\sqrt{3}i)(1-\\sqrt{3}i)}{(4\\sqrt{5})^2}=\\frac{4}{80}=\\frac{1}{20}$이므로 $z^n\\overline{z^n}=\\left(\\frac{1}{20}\\right)^n$이다. 따라서 $10^{-8}<\\left(\\frac{1}{20}\\right)^n<10^{-2}$이다. $20^2=400<10^3,\\ 20^3=8000<10^4$이므로 $20^n>10^8$을 만족하려면 $n\\ge6$이고, $20^5=3200000<10^8,\\ 20^6=64000000<10^8,\\ 20^7=128000000>10^8$이므로 $n\\le6$이다. 따라서 $n=6$이다. 그러나 $n$은 $6$의 배수이면서 $10\\le n\\le100$이므로 조건을 만족하는 값은 $n=12$뿐이다. 따라서 $b=1$이다. 그러므로 $a-b=15-1=14$이다."
  },
  {
    "id": 20,
    "level": "중",
    "category": "나머지 정리",
    "originalCategory": "나머지 정리",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-02",
    "standardUnit": "항등식과 나머지정리",
    "standardUnitOrder": 2,
    "content": "[서답형(서술형)1] 다항식 $f(x)$는 $(x-1)$을 인수로 가지고, $f(x)$를 $(x-3)$으로 나누었을 때 나머지가 2이다. $f(x)$를 $(x-1)(x-3)$으로 나누었을 때, 나머지 $R(x)$를 구하는 과정을 풀이과정과 함께 서술하시오. [4점]",
    "choices": [],
    "answer": "$x-1$",
    "solution": "$R(x)=ax+b$라 하면 $f(1)=0, f(3)=2$이다. $R(1)=a+b=0, R(3)=3a+b=2$를 연립하면 $2a=2$에서 $a=1, b=-1$이다. 따라서 $R(x)=x-1$이다."
  },
  {
    "id": 21,
    "level": "중",
    "category": "이차함수의 활용",
    "originalCategory": "이차함수의 활용",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-13",
    "standardUnit": "이차함수",
    "standardUnitOrder": 13,
    "content": "[서답형(서술형)2] 구조 로봇이 $2\\text{m}$ 높이의 바위 위에서 점프하여 바다로 뛰어내린 지 $t$초 후의 수면으로부터의 높이 $h\\text{m}$는 $$h(t)=-5t^2+4t+2$$와 같이 나타낼 수 있다고 한다. 다음 물음에 답하시오. (단, 로봇의 길이는 생각하지 않는다.) [총 5점]\n\n(1) 점프한 지 몇 초 후에 수면에 닿는지 구하는 과정을 풀이과정과 함께 서술하시오. [1점]\n(2) 점프한 지 1초 이내에 이 로봇의 수면으로부터의 최대 높이를 구하는 과정을 풀이과정과 함께 서술하시오. [2점]\n(3) 점프한 지 1초 이내에 이 로봇의 수면으로부터의 최소 높이를 구하는 과정을 풀이과정과 함께 서술하시오. [2점]",
    "choices": [],
    "answer": "(1) $\\frac{2+\\sqrt{14}}{5}$초 (2) $\\frac{14}{5}\\text{m}$ (3) $1\\text{m}$",
    "solution": "(1) $h(t)=0$에서 $-5t^2+4t+2=0$이므로 근의 공식에 의해 $t=\\frac{-4\\pm\\sqrt{16+40}}{-10} = \\frac{2\\pm\\sqrt{14}}{5}$이다. $t>0$이므로 $t=\\frac{2+\\sqrt{14}}{5}$초이다. (2) $h(t)=-5(t-\\frac{2}{5})^2+\\frac{14}{5}$이므로 $t=\\frac{2}{5}$일 때 최대 높이 $\\frac{14}{5}\\text{m}$를 갖는다. (3) $0 \\le t \\le 1$ 범위에서 $h(0)=2, h(1)=1$이므로 최소 높이는 $1\\text{m}$이다."
  },
  {
    "id": 22,
    "level": "중",
    "category": "다항식의 인수분해",
    "originalCategory": "다항식의 인수분해",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-03",
    "standardUnit": "인수분해",
    "standardUnitOrder": 3,
    "content": "[서답형(서술형)3] 삼차다항식 $f(x)=x^{3}-2x+4$에 대하여 다음 물음에 답하시오. [총 5점]\n\n(1) 다항식 $f(x)$를 인수분해하는 과정을 풀이과정과 함께 서술하시오. (단, 특별한 언급이 없는 경우에는 계수가 유리수인 범위에서 인수분해한다.) [2점]\n(2) 삼차방정식 $f(x)=0$을 푸는 과정을 풀이과정과 함께 서술하시오. [2점]\n(3) 다항식 $f(x)$를 복소수 범위에서 인수분해하는 과정을 풀이과정과 함께 서술하시오. [1점]",
    "choices": [],
    "answer": "(1) $(x+2)(x^2-2x+2)$ (2) $x=-2, 1\\pm i$ (3) $(x+2)(x-1-i)(x-1+i)$",
    "solution": "(1) 조립제법 $-2 | 1, 0, -2, 4 \\to 1, -2, 2, 0$을 통해 $(x+2)(x^2-2x+2)$를 얻는다. (2) $x^2-2x+2=0$에서 $x=1\\pm i$이므로 근은 $-2, 1\\pm i$이다. (3) 구한 근을 이용하여 $(x+2)(x-(1+i))(x-(1-i))$로 인수분해한다."
  },
  {
    "id": 23,
    "level": "상",
    "category": "연립이차방정식",
    "originalCategory": "연립이차방정식",
    "standardCourse": "수학(상)",
    "standardUnitKey": "H15-SA-07",
    "standardUnit": "여러 가지 방정식",
    "standardUnitOrder": 7,
    "content": "[서답형(서술형)4] 연립방정식 $\\begin{cases} x^2+3y^2-4xy-6y+2x=0 \\\\ 3x^2+2xy+3y^2-4k^2=0 \\end{cases}$을 만족하는 두 실수 $x, y$에 대해 정확히 세 쌍의 해를 갖도록 하는 $k$의 값을 구하는 과정을 풀이과정과 함께 서술하시오. (단, $k$는 양의 실수이다.) [6점]",
    "choices": [],
    "answer": "$1$",
    "solution": "$(x-3y)(x-y+2)=0$에서 (i) $x=3y$일 때 $36y^2=4k^2$에서 해가 2개 나온다. (ii) $x=y-2$를 대입하면 $8y^2-16y+12-4k^2=0$이며 세 쌍의 해를 위해 중근을 가져야 하므로 $D/4 = (-8)^2-8(12-4k^2) = -32+32k^2=0$에서 $k=1$이다."
  }
];